// ============================================
// TradePilot AI — Data Layer
// ============================================

/// ---- Countries ----
const COUNTRIES = [
  { code: 'TH', name: 'ไทย', enName: 'Thailand', flag: '🇹🇭' },
  { code: 'CN', name: 'จีน', enName: 'China', flag: '🇨🇳' },
  { code: 'JP', name: 'ญี่ปุ่น', enName: 'Japan', flag: '🇯🇵' },
  { code: 'US', name: 'สหรัฐอเมริกา', enName: 'United States', flag: '🇺🇸' },
  { code: 'GB', name: 'สหราชอาณาจักร', enName: 'United Kingdom', flag: '🇬🇧' },
  { code: 'DE', name: 'เยอรมนี', enName: 'Germany', flag: '🇩🇪' },
  { code: 'VN', name: 'เวียดนาม', enName: 'Vietnam', flag: '🇻🇳' },
  { code: 'MY', name: 'มาเลเซีย', enName: 'Malaysia', flag: '🇲🇾' },
  { code: 'SG', name: 'สิงคโปร์', enName: 'Singapore', flag: '🇸🇬' },
  { code: 'KR', name: 'เกาหลีใต้', enName: 'South Korea', flag: '🇰🇷' },
  { code: 'TW', name: 'ไต้หวัน', enName: 'Taiwan', flag: '🇹🇼' },
  { code: 'IN', name: 'อินเดีย', enName: 'India', flag: '🇮🇳' },
  { code: 'AU', name: 'ออสเตรเลีย', enName: 'Australia', flag: '🇦🇺' },
  { code: 'ID', name: 'อินโดนีเซีย', enName: 'Indonesia', flag: '🇮🇩' },
  { code: 'PH', name: 'ฟิลิปปินส์', enName: 'Philippines', flag: '🇵🇭' },
  { code: 'AF', name: 'อัฟกานิสถาน', enName: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AL', name: 'แอลเบเนีย', enName: 'Albania', flag: '🇦🇱' },
  { code: 'DZ', name: 'แอลจีเรีย', enName: 'Algeria', flag: '🇩🇿' },
  { code: 'AD', name: 'อันดอร์รา', enName: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', name: 'แองโกลา', enName: 'Angola', flag: '🇦🇴' },
  { code: 'AG', name: 'แอนติกาและบาร์บูดา', enName: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'AR', name: 'อาร์เจนตินา', enName: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', name: 'อาร์เมเนีย', enName: 'Armenia', flag: '🇦🇲' },
  { code: 'AT', name: 'ออสเตรีย', enName: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', name: 'อาเซอร์ไบจาน', enName: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BS', name: 'บาฮามาส', enName: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', name: 'บาห์เรน', enName: 'Bahrain', flag: '🇧🇭' },
  { code: 'BD', name: 'บังกลาเทศ', enName: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', name: 'บาร์เบโดส', enName: 'Barbados', flag: '🇧🇧' },
  { code: 'BY', name: 'เบลารุส', enName: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', name: 'เบลเยียม', enName: 'Belgium', flag: '🇧🇪' },
  { code: 'BZ', name: 'เบลีซ', enName: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'เบนิน', enName: 'Benin', flag: '🇧🇯' },
  { code: 'BT', name: 'ภูฏาน', enName: 'Bhutan', flag: '🇧🇹' },
  { code: 'BO', name: 'โบลิเวีย', enName: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', name: 'บอสเนียและเฮอร์เซโกวีนา', enName: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BW', name: 'บอตสวานา', enName: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', name: 'บราซิล', enName: 'Brazil', flag: '🇧🇷' },
  { code: 'BN', name: 'บรูไน', enName: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', name: 'บัลแกเรีย', enName: 'Bulgaria', flag: '🇧🇬' },
  { code: 'BF', name: 'บูร์กินาฟาโซ', enName: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'บุรุนดี', enName: 'Burundi', flag: '🇧🇮' },
  { code: 'KH', name: 'กัมพูชา', enName: 'Cambodia', flag: '🇰🇭' },
  { code: 'CM', name: 'แคเมอรูน', enName: 'Cameroon', flag: '🇨🇲' },
  { code: 'CA', name: 'แคนาดา', enName: 'Canada', flag: '🇨🇦' },
  { code: 'CV', name: 'เคปเวิร์ด', enName: 'Cape Verde', flag: '🇨🇻' },
  { code: 'CF', name: 'สาธารณรัฐแอฟริกากลาง', enName: 'Central African Republic', flag: '🇨🇫' },
  { code: 'TD', name: 'ชาด', enName: 'Chad', flag: '🇹🇩' },
  { code: 'CL', name: 'ชิลี', enName: 'Chile', flag: '🇨🇱' },
  { code: 'CO', name: 'โคลอมเบีย', enName: 'Colombia', flag: '🇨🇴' },
  { code: 'KM', name: 'คอโมรอส', enName: 'Comoros', flag: '🇰🇲' },
  { code: 'CG', name: 'คองโก', enName: 'Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'สาธารณรัฐประชาธิปไตยคองโก', enName: 'Democratic Republic of the Congo', flag: '🇨🇩' },
  { code: 'CR', name: 'คอสตาริกา', enName: 'Costa Rica', flag: '🇨🇷' },
  { code: 'HR', name: 'โครเอเชีย', enName: 'Croatia', flag: '🇭🇷' },
  { code: 'CU', name: 'คิวบา', enName: 'Cuba', flag: '🇨🇺' },
  { code: 'CY', name: 'ไซปรัส', enName: 'Cyprus', flag: '🇨🇾' },
  { code: 'CZ', name: 'เช็กเกีย', enName: 'Czechia', flag: '🇨🇿' },
  { code: 'DK', name: 'เดนมาร์ก', enName: 'Denmark', flag: '🇩🇰' },
  { code: 'DJ', name: 'จิบูตี', enName: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', name: 'โดมินิกา', enName: 'Dominica', flag: '🇩🇲' },
  { code: 'DO', name: 'สาธารณรัฐโดมินิกัน', enName: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'EC', name: 'เอกวาดอร์', enName: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', name: 'อียิปต์', enName: 'Egypt', flag: '🇪🇬' },
  { code: 'SV', name: 'เอลซัลวาดอร์', enName: 'El Salvador', flag: '🇸🇻' },
  { code: 'GQ', name: 'อิเควทอเรียลกินี', enName: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'ER', name: 'เอริเทรีย', enName: 'Eritrea', flag: '🇪🇷' },
  { code: 'EE', name: 'เอสโตเนีย', enName: 'Estonia', flag: '🇪🇪' },
  { code: 'SZ', name: 'เอสวาตีนี', enName: 'Eswatini', flag: '🇸🇿' },
  { code: 'ET', name: 'เอธิโอเปีย', enName: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FJ', name: 'ฟิจิ', enName: 'Fiji', flag: '🇫🇯' },
  { code: 'FI', name: 'ฟินแลนด์', enName: 'Finland', flag: '🇫🇮' },
  { code: 'FR', name: 'ฝรั่งเศส', enName: 'France', flag: '🇫🇷' },
  { code: 'GA', name: 'กาบอง', enName: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'แกมเบีย', enName: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', name: 'จอร์เจีย', enName: 'Georgia', flag: '🇬🇪' },
  { code: 'GH', name: 'กานา', enName: 'Ghana', flag: '🇬🇭' },
  { code: 'GR', name: 'กรีซ', enName: 'Greece', flag: '🇬🇷' },
  { code: 'GD', name: 'เกรเนดา', enName: 'Grenada', flag: '🇬🇩' },
  { code: 'GT', name: 'กัวเตมาลา', enName: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', name: 'กินี', enName: 'Guinea', flag: '🇬🇳' },
  { code: 'GW', name: 'กินี-บิสเซา', enName: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'กายอานา', enName: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'เฮติ', enName: 'Haiti', flag: '🇭🇹' },
  { code: 'HN', name: 'ฮอนดูรัส', enName: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', name: 'ฮังการี', enName: 'Hungary', flag: '🇭🇺' },
  { code: 'IS', name: 'ไอซ์แลนด์', enName: 'Iceland', flag: '🇮🇸' },
  { code: 'IR', name: 'อิหร่าน', enName: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', name: 'อิรัก', enName: 'Iraq', flag: '🇮🇶' },
  { code: 'IE', name: 'ไอร์แลนด์', enName: 'Ireland', flag: '🇮🇪' },
  { code: 'IL', name: 'อิสราเอล', enName: 'Israel', flag: '🇮🇱' },
  { code: 'IT', name: 'อิตาลี', enName: 'Italy', flag: '🇮🇹' },
  { code: 'CI', name: 'โกตดิวัวร์', enName: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'JM', name: 'จาเมกา', enName: 'Jamaica', flag: '🇯🇲' },
  { code: 'JO', name: 'จอร์แดน', enName: 'Jordan', flag: '🇯🇴' },
  { code: 'KZ', name: 'คาซัคสถาน', enName: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', name: 'เคนยา', enName: 'Kenya', flag: '🇰🇪' },
  { code: 'KI', name: 'คิริบาส', enName: 'Kiribati', flag: '🇰🇮' },
  { code: 'KP', name: 'เกาหลีเหนือ', enName: 'North Korea', flag: '🇰🇵' },
  { code: 'KW', name: 'คูเวต', enName: 'Kuwait', flag: '🇰🇼' },
  { code: 'KG', name: 'คีร์กีซสถาน', enName: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'LA', name: 'ลาว', enName: 'Laos', flag: '🇱🇦' },
  { code: 'LV', name: 'ลัตเวีย', enName: 'Latvia', flag: '🇱🇻' },
  { code: 'LB', name: 'เลบานอน', enName: 'Lebanon', flag: '🇱🇧' },
  { code: 'LS', name: 'เลโซโท', enName: 'Lesotho', flag: '🇱🇸' },
  { code: 'LR', name: 'ไลบีเรีย', enName: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'ลิเบีย', enName: 'Libya', flag: '🇱🇾' },
  { code: 'LI', name: 'ลิกเตนสไตน์', enName: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'ลิทัวเนีย', enName: 'Lithuania', flag: '🇱🇹' },
  { code: 'LU', name: 'ลักเซมเบิร์ก', enName: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MG', name: 'มาดากัสการ์', enName: 'Madagascar', flag: '🇲🇬' },
  { code: 'MW', name: 'มาลาวี', enName: 'Malawi', flag: '🇲🇼' },
  { code: 'MV', name: 'มัลดีฟส์', enName: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', name: 'มาลี', enName: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'มอลตา', enName: 'Malta', flag: '🇲🇹' },
  { code: 'MH', name: 'หมู่เกาะมาร์แชลล์', enName: 'Marshall Islands', flag: '🇲🇭' },
  { code: 'MR', name: 'มอริเตเนีย', enName: 'Mauritania', flag: '🇲🇷' },
  { code: 'MU', name: 'มอริเชียส', enName: 'Mauritius', flag: '🇲🇺' },
  { code: 'MX', name: 'เม็กซิโก', enName: 'Mexico', flag: '🇲🇽' },
  { code: 'FM', name: 'ไมโครนีเซีย', enName: 'Micronesia', flag: '🇫🇲' },
  { code: 'MD', name: 'มอลโดวา', enName: 'Moldova', flag: '🇲🇩' },
  { code: 'MC', name: 'โมนาโก', enName: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', name: 'มองโกเลีย', enName: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', name: 'มอนเตเนโกร', enName: 'Montenegro', flag: '🇲🇪' },
  { code: 'MA', name: 'โมร็อกโก', enName: 'Morocco', flag: '🇲🇦' },
  { code: 'MZ', name: 'โมซัมบิก', enName: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', name: 'เมียนมา', enName: 'Myanmar', flag: '🇲🇲' },
  { code: 'NA', name: 'นามิเบีย', enName: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', name: 'นาอูรู', enName: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'เนปาล', enName: 'Nepal', flag: '🇳🇵' },
  { code: 'NL', name: 'เนเธอร์แลนด์', enName: 'Netherlands', flag: '🇳🇱' },
  { code: 'NZ', name: 'นิวซีแลนด์', enName: 'New Zealand', flag: '🇳🇿' },
  { code: 'NI', name: 'นิการากัว', enName: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'ไนเจอร์', enName: 'Niger', flag: '🇳🇪' },
  { code: 'NG', name: 'ไนจีเรีย', enName: 'Nigeria', flag: '🇳🇬' },
  { code: 'NO', name: 'นอร์เวย์', enName: 'Norway', flag: '🇳🇴' },
  { code: 'OM', name: 'โอมาน', enName: 'Oman', flag: '🇴🇲' },
  { code: 'PK', name: 'ปากีสถาน', enName: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'ปาเลา', enName: 'Palau', flag: '🇵🇼' },
  { code: 'PA', name: 'ปานามา', enName: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'ปาปัวนิวกินี', enName: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'PY', name: 'ปารากวัย', enName: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'เปรู', enName: 'Peru', flag: '🇵🇪' },
  { code: 'PL', name: 'โปแลนด์', enName: 'Poland', flag: '🇵🇱' },
  { code: 'PT', name: 'โปรตุเกส', enName: 'Portugal', flag: '🇵🇹' },
  { code: 'QA', name: 'กาตาร์', enName: 'Qatar', flag: '🇶🇦' },
  { code: 'RO', name: 'โรมาเนีย', enName: 'Romania', flag: '🇷🇴' },
  { code: 'RU', name: 'รัสเซีย', enName: 'Russia', flag: '🇷🇺' },
  { code: 'RW', name: 'รวันดา', enName: 'Rwanda', flag: '🇷🇼' },
  { code: 'KN', name: 'เซนต์คิตส์และเนวิส', enName: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: 'LC', name: 'เซนต์ลูเซีย', enName: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'VC', name: 'เซนต์วินเซนต์และเกรนาดีนส์', enName: 'Saint Vincent and the Grenadines', flag: '🇨🇻' },
  { code: 'WS', name: 'ซามัว', enName: 'Samoa', flag: '🇼🇸' },
  { code: 'SM', name: 'ซานมารีโน', enName: 'San Marino', flag: '🇸🇲' },
  { code: 'ST', name: 'เซาตูเมและปรินซิปี', enName: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: 'SA', name: 'ซาอุดีอาระเบีย', enName: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'SN', name: 'เซเนกัล', enName: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', name: 'เซอร์เบีย', enName: 'Serbia', flag: '🇷🇸' },
  { code: 'SC', name: 'เซเชลส์', enName: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'เซียร์ราลีโอน', enName: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SK', name: 'สโลวาเกีย', enName: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', name: 'สโลวีเนีย', enName: 'Slovenia', flag: '🇸🇮' },
  { code: 'SB', name: 'หมู่เกาะโซโลมอน', enName: 'Solomon Islands', flag: '🇸🇧' },
  { code: 'SO', name: 'โซมาเลีย', enName: 'Somalia', flag: '🇸🇴' },
  { code: 'ZA', name: 'แอฟริกาใต้', enName: 'South Africa', flag: '🇿🇦' },
  { code: 'SS', name: 'เซาท์ซูดาน', enName: 'South Sudan', flag: '🇸🇸' },
  { code: 'ES', name: 'สเปน', enName: 'Spain', flag: '🇪🇸' },
  { code: 'LK', name: 'ศรีลังกา', enName: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SD', name: 'ซูดาน', enName: 'Sudan', flag: '🇸🇩' },
  { code: 'SR', name: 'ซูรินาม', enName: 'Suriname', flag: '🇸🇷' },
  { code: 'SE', name: 'สวีเดน', enName: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', name: 'สวิตเซอร์แลนด์', enName: 'Switzerland', flag: '🇨🇭' },
  { code: 'SY', name: 'ซีเรีย', enName: 'Syria', flag: '🇸🇾' },
  { code: 'TJ', name: 'ทาจิกิสถาน', enName: 'Tajikistan', flag: '🇹🇯' },
  { code: 'TZ', name: 'แทนซาเนีย', enName: 'Tanzania', flag: '🇹🇿' },
  { code: 'TL', name: 'ติมอร์-เลสเต', enName: 'Timor-Leste', flag: '🇹🇱' },
  { code: 'TG', name: 'โตโก', enName: 'Togo', flag: '🇹🇬' },
  { code: 'TO', name: 'ตองกา', enName: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'ตรินิแดดและโตเบโก', enName: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'ตูนิเซีย', enName: 'Tunisia', flag: '🇹🇳' },
  { code: 'TR', name: 'ตุรกี', enName: 'Turkey', flag: '🇹🇷' },
  { code: 'TM', name: 'ทิวร์กเมนิสถาน', enName: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'TV', name: 'ตูวาลู', enName: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UG', name: 'ยูแกนดา', enName: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', name: 'ยูเครน', enName: 'Ukraine', flag: '🇺🇦' },
  { code: 'AE', name: 'สหรัฐอาหรับเอมิเรตส์', enName: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'UY', name: 'อุรุกวัย', enName: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', name: 'อุซเบกิสถาน', enName: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VU', name: 'วานูอาตู', enName: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VA', name: 'นครรัฐวาติกัน', enName: 'Vatican City', flag: '🇻🇦' },
  { code: 'VE', name: 'เวเนซุเอลา', enName: 'Venezuela', flag: '🇻🇪' },
  { code: 'YE', name: 'เยเมน', enName: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', name: 'แซมเบีย', enName: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'ซิมบับเว', enName: 'Zimbabwe', flag: '🇿🇼' }
];

// ---- Product Categories ----
const PRODUCT_CATEGORIES = [
  { id: 'food', name: 'อาหารและเครื่องดื่ม', icon: 'soup', dutyRate: 40 },
  { id: 'cosmetics', name: 'เครื่องสำอาง / ยา / เวชภัณฑ์', icon: 'sparkles', dutyRate: 30 },
  { id: 'electronics', name: 'อิเล็กทรอนิกส์', icon: 'smartphone', dutyRate: 5 },
  { id: 'textiles', name: 'เสื้อผ้า / สิ่งทอ', icon: 'shirt', dutyRate: 30 },
  { id: 'machinery', name: 'เครื่องจักร / อุปกรณ์', icon: 'settings', dutyRate: 5 },
  { id: 'chemicals', name: 'เคมีภัณฑ์', icon: 'flask-conical', dutyRate: 3 },
  { id: 'agriculture', name: 'สินค้าเกษตร', icon: 'sprout', dutyRate: 35 },
  { id: 'vehicles', name: 'ยานพาหนะ / อะไหล่', icon: 'car', dutyRate: 60 },
  { id: 'jewelry', name: 'อัญมณี / เครื่องประดับ', icon: 'gem', dutyRate: 20 },
  { id: 'general', name: 'สินค้าทั่วไป', icon: 'package', dutyRate: 15 },
];

// ---- VAT Rate ----
const VAT_RATE = 0.07; // 7%

// ---- Checklists ----
const CHECKLISTS = {
  import: {
    general: [
      {
        title: 'ลงทะเบียนผู้นำเข้า',
        desc: 'สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs',
        docs: ['บัตรประชาชน/หนังสือเดินทาง', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'ตรวจสอบพิกัดศุลกากร (HS Code)',
        desc: 'หาพิกัดอัตราศุลกากร (HS Code) ของสินค้าที่ต้องการนำเข้า เพื่อทราบอัตราอากรและข้อกำหนด',
        docs: ['HS Code 8 หลัก'],
      },
      {
        title: 'ตรวจสอบว่าสินค้าต้องขอใบอนุญาตหรือไม่',
        desc: 'สินค้าบางประเภทต้องขออนุญาตจากหน่วยงานที่เกี่ยวข้อง เช่น อย., กรมวิชาการเกษตร, สำนักงาน กสทช.',
        docs: ['ใบอนุญาตนำเข้า (ถ้ามี)'],
      },
      {
        title: 'เตรียมเอกสารการค้า',
        desc: 'จัดเตรียมเอกสารให้ครบถ้วน ข้อมูลต้องตรงกันทุกเอกสาร (ชื่อ, จำนวน, มูลค่า)',
        docs: ['Commercial Invoice', 'Packing List', 'Bill of Lading / Air Waybill'],
      },
      {
        title: 'ขอหนังสือรับรองแหล่งกำเนิดสินค้า (CO)',
        desc: 'หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี ต้องมี Certificate of Origin จากประเทศต้นทาง',
        docs: ['Certificate of Origin (CO)'],
      },
      {
        title: 'จัดหา Freight Forwarder / Customs Broker',
        desc: 'แนะนำให้ใช้ตัวแทนออกของ (Customs Broker) ที่มีใบอนุญาตเพื่อดำเนินพิธีการศุลกากร',
        docs: ['สัญญาจ้างตัวแทน'],
      },
      {
        title: 'ยื่นใบขนสินค้าขาเข้า (e-Import)',
        desc: 'ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร ระบบจะตรวจสอบข้อมูลอัตโนมัติ',
        docs: ['ใบขนสินค้า (Customs Declaration)'],
      },
      {
        title: 'ชำระอากรและภาษี',
        desc: 'ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment ของกรมศุลกากร',
        docs: ['ใบเสร็จชำระอากร', 'ใบเสร็จ VAT'],
      },
      {
        title: 'รอตรวจปล่อยสินค้า',
        desc: 'สินค้าจะถูกจัดเข้า Green Line (ไม่ตรวจ) หรือ Red Line (ต้องตรวจ) ตามระดับความเสี่ยง',
        docs: [],
      },
      {
        title: 'รับสินค้า',
        desc: 'เมื่อผ่านการตรวจปล่อยแล้ว สามารถรับสินค้าจากท่าเรือ/สนามบินได้',
        docs: ['ใบปล่อยสินค้า (Delivery Order)'],
      },
    ],
    food: [
      {
        title: 'ลงทะเบียนผู้นำเข้า',
        desc: 'สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate',
        docs: ['บัตรประชาชน/หนังสือเดินทาง', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'ขอใบอนุญาตนำเข้าอาหาร (อย.)',
        desc: 'ยื่นขออนุญาตนำเข้าอาหารจากสำนักงานคณะกรรมการอาหารและยา (อย.) ต้องขอก่อนนำเข้า',
        docs: ['ใบอนุญาตนำเข้าอาหาร', 'ฉลากอาหาร (ภาษาไทย)', 'ผลวิเคราะห์คุณภาพ'],
      },
      {
        title: 'ตรวจสอบพิกัดศุลกากร (HS Code)',
        desc: 'หาพิกัดอัตราศุลกากรของสินค้าอาหาร อัตราอากรอาหารมักอยู่ที่ 30-50%',
        docs: ['HS Code 8 หลัก'],
      },
      {
        title: 'เตรียมเอกสารการค้า + ใบรับรองสุขอนามัย',
        desc: 'นอกจากเอกสารปกติ ต้องมี Health Certificate และ Phytosanitary Certificate (สินค้าพืช)',
        docs: ['Commercial Invoice', 'Packing List', 'B/L or AWB', 'Health Certificate', 'Phytosanitary Certificate'],
      },
      {
        title: 'ขอ Certificate of Origin (CO)',
        desc: 'หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี',
        docs: ['Certificate of Origin'],
      },
      {
        title: 'ยื่นใบขนสินค้า (e-Import)',
        desc: 'ยื่นใบขนสินค้าผ่านระบบ e-Customs พร้อมแนบเอกสารประกอบ',
        docs: ['ใบขนสินค้า'],
      },
      {
        title: 'ตรวจสอบจาก อย. ที่ด่านอาหารและยา',
        desc: 'สินค้าอาหารจะถูกตรวจสอบที่ด่านอาหารและยา ก่อนปล่อยออกจากท่าเรือ/สนามบิน',
        docs: ['ผลการตรวจสอบจาก อย.'],
      },
      {
        title: 'ชำระอากรและภาษี',
        desc: 'ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment',
        docs: ['ใบเสร็จชำระอากร'],
      },
      {
        title: 'รับสินค้า',
        desc: 'เมื่อผ่านการตรวจปล่อยจากศุลกากรและ อย. แล้ว สามารถรับสินค้าได้',
        docs: ['ใบปล่อยสินค้า'],
      },
    ],
    cosmetics: [
      {
        title: 'ลงทะเบียนผู้นำเข้า',
        desc: 'สมัครเป็นผู้นำเข้ากับกรมศุลกากร',
        docs: ['บัตรประชาชน', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'จดแจ้งเครื่องสำอาง / ขออนุญาตยา',
        desc: 'เครื่องสำอางต้องจดแจ้งกับ อย. ก่อนนำเข้า ยาต้องขอใบอนุญาตนำเข้ายาแผนปัจจุบัน',
        docs: ['ใบจดแจ้งเครื่องสำอาง / ใบอนุญาตนำเข้ายา', 'รายการส่วนผสม (INCI)', 'ฉลากภาษาไทย'],
      },
      {
        title: 'ตรวจสอบสารต้องห้ามในส่วนผสม',
        desc: 'ตรวจสอบว่าผลิตภัณฑ์ไม่มีสารต้องห้ามตามประกาศ อย.',
        docs: ['Certificate of Analysis (COA)', 'MSDS'],
      },
      {
        title: 'เตรียมเอกสารการค้า',
        desc: 'จัดเตรียมเอกสารครบถ้วน',
        docs: ['Commercial Invoice', 'Packing List', 'B/L or AWB'],
      },
      {
        title: 'ยื่นใบขนสินค้า (e-Import)',
        desc: 'ยื่นใบขนผ่านระบบ e-Customs',
        docs: ['ใบขนสินค้า'],
      },
      {
        title: 'ตรวจสอบจาก อย.',
        desc: 'สินค้าจะถูกตรวจสอบที่ด่านอาหารและยา',
        docs: ['ผลการตรวจสอบ'],
      },
      {
        title: 'ชำระอากรและภาษี',
        desc: 'ชำระอากรขาเข้า + VAT 7%',
        docs: ['ใบเสร็จ'],
      },
      {
        title: 'รับสินค้า',
        desc: 'รับสินค้าหลังผ่านการตรวจปล่อย',
        docs: ['ใบปล่อยสินค้า'],
      },
    ],
    electronics: [
      {
        title: 'ลงทะเบียนผู้นำเข้า',
        desc: 'สมัครเป็นผู้นำเข้ากับกรมศุลกากร',
        docs: ['บัตรประชาชน', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'ตรวจสอบ HS Code และข้อกำหนด มอก.',
        desc: 'สินค้าอิเล็กทรอนิกส์บางชนิดต้องมีมาตรฐาน มอก. (TIS) และอาจต้องขอใบอนุญาตจาก กสทช.',
        docs: ['HS Code', 'ใบรับรอง มอก. (ถ้ามี)', 'ใบอนุญาต กสทช. (ถ้ามี)'],
      },
      {
        title: 'เตรียมเอกสารการค้า',
        desc: 'จัดเตรียมเอกสารครบถ้วน',
        docs: ['Commercial Invoice', 'Packing List', 'B/L or AWB'],
      },
      {
        title: 'ขอ Certificate of Origin (CO)',
        desc: 'อิเล็กทรอนิกส์หลายรายการได้สิทธิ FTA อัตราอากร 0%',
        docs: ['Certificate of Origin'],
      },
      {
        title: 'ยื่นใบขนสินค้า (e-Import)',
        desc: 'ยื่นใบขนผ่านระบบ e-Customs',
        docs: ['ใบขนสินค้า'],
      },
      {
        title: 'ชำระอากรและภาษี',
        desc: 'ชำระอากรขาเข้า (อิเล็กทรอนิกส์มักอยู่ที่ 0-10%) + VAT 7%',
        docs: ['ใบเสร็จ'],
      },
      {
        title: 'รับสินค้า',
        desc: 'รับสินค้าหลังผ่านการตรวจปล่อย',
        docs: ['ใบปล่อยสินค้า'],
      },
    ],
  },
  export: {
    general: [
      {
        title: 'ลงทะเบียนผู้ส่งออก',
        desc: 'สมัครเป็นผู้ส่งออกกับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs',
        docs: ['บัตรประชาชน/หนังสือเดินทาง', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'ตรวจสอบกฎระเบียบของประเทศปลายทาง',
        desc: 'ศึกษาข้อกำหนดการนำเข้าของประเทศปลายทาง เช่น มาตรฐาน, ฉลาก, ใบอนุญาต',
        docs: ['กฎระเบียบประเทศปลายทาง'],
      },
      {
        title: 'ตรวจสอบว่าสินค้าเป็นสินค้าควบคุมส่งออกหรือไม่',
        desc: 'สินค้าบางประเภทต้องขออนุญาตก่อนส่งออก เช่น ข้าว, น้ำตาล, อาวุธ, โบราณวัตถุ',
        docs: ['ใบอนุญาตส่งออก (ถ้ามี)'],
      },
      {
        title: 'เตรียมเอกสารการค้า',
        desc: 'จัดเตรียม Invoice, Packing List และเอกสารขนส่ง',
        docs: ['Commercial Invoice', 'Packing List', 'Bill of Lading / Air Waybill'],
      },
      {
        title: 'ขอหนังสือรับรองแหล่งกำเนิดสินค้า (CO)',
        desc: 'ขอ CO จากกรมการค้าต่างประเทศ หรือหอการค้าไทย เพื่อให้ผู้ซื้อใช้สิทธิ FTA',
        docs: ['Certificate of Origin (CO)'],
      },
      {
        title: 'ยื่นใบขนสินค้าขาออก (e-Export)',
        desc: 'ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร',
        docs: ['ใบขนสินค้าขาออก'],
      },
      {
        title: 'นำสินค้าเข้าท่าเรือ/สนามบิน',
        desc: 'นำสินค้าไปยังท่าเรือหรือสนามบินตามที่ระบุ พร้อมเอกสารประกอบ',
        docs: [],
      },
      {
        title: 'ตรวจปล่อยสินค้าขาออก',
        desc: 'รอการตรวจปล่อยจากศุลกากร (ส่วนใหญ่สินค้าส่งออกจะเข้า Green Line)',
        docs: ['ใบปล่อยสินค้า'],
      },
    ],
  },
};

// ---- Prohibited Items ----
const PROHIBITED_ITEMS = [
  {
    keywords: ['ยาเสพติด', 'เฮโรอีน', 'โคเคน', 'ฝิ่น', 'กัญชา', 'ยาบ้า', 'ยาไอซ์', 'กระท่อม', 'narcotics', 'drugs', 'heroin', 'cocaine', 'opium', 'marijuana', 'methamphetamine'],
    name: 'ยาเสพติดให้โทษ',
    status: 'prohibited',
    reason: 'ห้ามนำเข้าและส่งออกโดยเด็ดขาด ตามพระราชบัญญัติยาเสพติดให้โทษ ผู้ฝ่าฝืนมีโทษจำคุกสูงสุดตลอดชีวิตหรือประหารชีวิต',
  },
  {
    keywords: ['บุหรี่ไฟฟ้า', 'vape', 'e-cigarette', 'pod', 'บุหรี่อิเล็กทรอนิกส์', 'น้ำยาบุหรี่', 'iqos', 'juul', 'พอด'],
    name: 'บุหรี่ไฟฟ้า / Vape / IQOS',
    status: 'prohibited',
    reason: 'ห้ามนำเข้า ขาย และครอบครองในประเทศไทย ตามคำสั่งคณะกรรมการคุ้มครองผู้บริโภค มีโทษจำคุกสูงสุด 5 ปี หรือปรับสูงสุด 500,000 บาท',
  },
  {
    keywords: ['สื่อลามก', 'หนังโป๊', 'pornography', 'obscene', 'สื่อลามกอนาจาร'],
    name: 'สื่อลามกอนาจาร',
    status: 'prohibited',
    reason: 'ห้ามนำเข้าสิ่งพิมพ์ ภาพ หรือสื่อลามกอนาจารทุกรูปแบบ',
  },
  {
    keywords: ['สินค้าปลอม', 'ของก๊อป', 'ของเลียนแบบ', 'ละเมิดลิขสิทธิ์', 'counterfeit', 'fake', 'ของปลอม', 'เลียนแบบแบรนด์'],
    name: 'สินค้าปลอม / ละเมิดทรัพย์สินทางปัญญา',
    status: 'prohibited',
    reason: 'ห้ามนำเข้าสินค้าที่ละเมิดลิขสิทธิ์ เครื่องหมายการค้า หรือสิทธิบัตร มีโทษจำคุกและปรับ',
  },
  {
    keywords: ['สัตว์ป่า', 'งาช้าง', 'ivory', 'กระดองเต่า', 'นอแรด', 'หนังจระเข้', 'สัตว์คุ้มครอง', 'CITES', 'wildlife'],
    name: 'สัตว์ป่าคุ้มครอง / ผลิตภัณฑ์จากสัตว์ป่า',
    status: 'prohibited',
    reason: 'ห้ามนำเข้า-ส่งออกสัตว์ป่าและผลิตภัณฑ์จากสัตว์ป่าที่อยู่ในบัญชี CITES ตามพระราชบัญญัติสงวนและคุ้มครองสัตว์ป่า',
  },
  {
    keywords: ['เงินปลอม', 'ธนบัตรปลอม', 'แสตมป์ปลอม', 'ตราปลอม', 'counterfeit currency', 'fake money'],
    name: 'เงินตราปลอม / ตราปลอม',
    status: 'prohibited',
    reason: 'ห้ามนำเข้าเงินตราปลอม เหรียญปลอม หรือดวงตราปลอมของรัฐบาลโดยเด็ดขาด',
  },
];

// ---- Restricted Items (ต้องมีใบอนุญาต) ----
const RESTRICTED_ITEMS = [
  {
    keywords: ['ยา', 'เวชภัณฑ์', 'ยาแผนปัจจุบัน', 'ยาสมุนไพร', 'วัคซีน', 'medicine', 'pharmaceutical', 'drug', 'ยารักษาโรค', 'อาหารเสริม', 'supplement'],
    name: 'ยา / เวชภัณฑ์ / อาหารเสริม',
    status: 'restricted',
    agency: 'สำนักงานคณะกรรมการอาหารและยา (อย.)',
    reason: 'ต้องขอใบอนุญาตนำเข้ายาจาก อย. ก่อนนำเข้า สำหรับใช้ส่วนตัวต้องมีใบรับรองแพทย์และนำเข้าได้ไม่เกิน 30 วัน',
    docs: ['ใบอนุญาตนำเข้ายา', 'ใบรับรองแพทย์ (กรณีส่วนตัว)'],
  },
  {
    keywords: ['เครื่องสำอาง', 'ครีม', 'skincare', 'cosmetic', 'makeup', 'แป้ง', 'ลิปสติก', 'ครีมกันแดด', 'เซรั่ม', 'serum'],
    name: 'เครื่องสำอาง',
    status: 'restricted',
    agency: 'สำนักงานคณะกรรมการอาหารและยา (อย.)',
    reason: 'ต้องจดแจ้งเครื่องสำอางกับ อย. ก่อนจำหน่าย ต้องมีฉลากภาษาไทยและไม่มีสารต้องห้าม',
    docs: ['ใบจดแจ้งเครื่องสำอาง', 'รายการส่วนผสม (INCI)', 'Certificate of Analysis'],
  },
  {
    keywords: ['อาวุธ', 'ปืน', 'กระสุน', 'ระเบิด', 'firearms', 'weapon', 'ammunition', 'gun', 'explosive'],
    name: 'อาวุธปืน / กระสุน / วัตถุระเบิด',
    status: 'restricted',
    agency: 'สำนักงานตำรวจแห่งชาติ',
    reason: 'ต้องขอใบอนุญาตจากนายทะเบียนอาวุธปืน สำนักงานตำรวจแห่งชาติ',
    docs: ['ใบอนุญาตนำเข้าอาวุธปืน'],
  },
  {
    keywords: ['พืช', 'เมล็ดพันธุ์', 'ผลไม้', 'ผัก', 'ดอกไม้', 'ต้นไม้', 'plant', 'seed', 'fruit', 'vegetable', 'flower'],
    name: 'พืช / เมล็ดพันธุ์ / ผลไม้สด',
    status: 'restricted',
    agency: 'กรมวิชาการเกษตร',
    reason: 'ต้องมีใบรับรองสุขอนามัยพืช (Phytosanitary Certificate) จากประเทศต้นทาง และอาจต้องขออนุญาตนำเข้าจากกรมวิชาการเกษตร',
    docs: ['Phytosanitary Certificate', 'ใบอนุญาตนำเข้า (บางชนิด)'],
  },
  {
    keywords: ['สัตว์', 'สัตว์เลี้ยง', 'สุนัข', 'แมว', 'ปลา', 'นก', 'animal', 'pet', 'dog', 'cat', 'bird', 'fish', 'สัตว์มีชีวิต'],
    name: 'สัตว์มีชีวิต / ผลิตภัณฑ์จากสัตว์',
    status: 'restricted',
    agency: 'กรมปศุสัตว์',
    reason: 'ต้องมีใบรับรองสุขภาพสัตว์ (Health Certificate) จากประเทศต้นทาง และขอใบอนุญาตนำเข้าจากกรมปศุสัตว์',
    docs: ['Health Certificate', 'ใบอนุญาตนำเข้าสัตว์', 'ใบรับรองการฉีดวัคซีน'],
  },
  {
    keywords: ['พระพุทธรูป', 'โบราณวัตถุ', 'ศิลปวัตถุ', 'antique', 'buddha', 'artifact', 'โบราณ'],
    name: 'พระพุทธรูป / โบราณวัตถุ / ศิลปวัตถุ',
    status: 'restricted',
    agency: 'กรมศิลปากร',
    reason: 'การส่งออกพระพุทธรูปหรือโบราณวัตถุต้องขออนุญาตจากกรมศิลปากร พระพุทธรูปสูงเกิน 13 ซม. ต้องมีใบอนุญาต',
    docs: ['ใบอนุญาตจากกรมศิลปากร'],
  },
  {
    keywords: ['วิทยุสื่อสาร', 'วอลกี้ทอลกี้', 'เครื่องส่งวิทยุ', 'radio', 'transceiver', 'walkie talkie', 'อุปกรณ์โทรคมนาคม', 'telecom'],
    name: 'อุปกรณ์โทรคมนาคม / วิทยุสื่อสาร',
    status: 'restricted',
    agency: 'สำนักงาน กสทช. (NBTC)',
    reason: 'เครื่องวิทยุคมนาคมต้องขอใบอนุญาตจาก กสทช. ก่อนนำเข้า',
    docs: ['ใบอนุญาตนำเข้าเครื่องวิทยุคมนาคม'],
  },
  {
    keywords: ['โดรน', 'drone', 'UAV', 'อากาศยานไร้คนขับ'],
    name: 'โดรน / อากาศยานไร้คนขับ',
    status: 'restricted',
    agency: 'สำนักงานการบินพลเรือนแห่งประเทศไทย (CAAT) + กสทช.',
    reason: 'ต้องขึ้นทะเบียนกับ CAAT และ กสทช. ก่อนใช้งาน น้ำหนักเกิน 2 กก. ต้องขอใบอนุญาตเพิ่มเติม',
    docs: ['ใบขึ้นทะเบียน CAAT', 'ใบอนุญาต กสทช.'],
  },
  {
    keywords: ['สุรา', 'เหล้า', 'เบียร์', 'ไวน์', 'แอลกอฮอล์', 'alcohol', 'beer', 'wine', 'liquor', 'whisky', 'whiskey', 'vodka'],
    name: 'สุรา / เครื่องดื่มแอลกอฮอล์',
    status: 'restricted',
    agency: 'กรมสรรพสามิต + กรมศุลกากร',
    reason: 'นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาตจากกรมสรรพสามิต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 1 ลิตร (ปลอดอากร)',
    docs: ['ใบอนุญาตนำเข้า', 'ใบอนุญาตขาย'],
  },
  {
    keywords: ['บุหรี่', 'ยาสูบ', 'ซิการ์', 'cigarette', 'tobacco', 'cigar'],
    name: 'บุหรี่ / ยาสูบ',
    status: 'restricted',
    agency: 'กรมสรรพสามิต + กรมศุลกากร',
    reason: 'นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 200 มวน หรือยาสูบ 250 กรัม',
    docs: ['ใบอนุญาตนำเข้า'],
  },
  {
    keywords: ['อาหาร', 'ขนม', 'อาหารแปรรูป', 'อาหารกระป๋อง', 'food', 'snack', 'canned food', 'instant noodle', 'มาม่า', 'บะหมี่', 'ซอส', 'เครื่องปรุง'],
    name: 'อาหาร / อาหารแปรรูป',
    status: 'restricted',
    agency: 'สำนักงานคณะกรรมการอาหารและยา (อย.)',
    reason: 'ต้องขอใบอนุญาตนำเข้าอาหารจาก อย. ต้องมีฉลากภาษาไทย และผ่านการตรวจสอบคุณภาพ',
    docs: ['ใบอนุญาตนำเข้าอาหาร', 'ฉลากภาษาไทย', 'ผลวิเคราะห์'],
  },
];

// ---- Warnings & Regulations ----
const WARNINGS = {
  // Global warnings (แสดงทุกกรณี)
  global: [
    {
      type: 'critical',
      icon: 'alert-octagon',
      title: 'ต้องลงทะเบียนเป็นผู้นำเข้า/ส่งออก',
      text: 'ก่อนดำเนินการนำเข้าหรือส่งออก ต้องลงทะเบียนกับกรมศุลกากรและมี Digital Certificate เพื่อใช้ระบบ e-Customs',
    },
    {
      type: 'important',
      icon: 'banknote',
      title: 'สินค้าทุกรายการต้องเสียภาษี VAT 7%',
      text: 'ตั้งแต่ปี 2024 สินค้านำเข้าทุกรายการรวมถึงมูลค่าต่ำกว่า 1,500 บาท ต้องเสียภาษีมูลค่าเพิ่ม (VAT) 7%',
    },
    {
      type: 'info',
      icon: 'file-text',
      title: 'เอกสารต้องตรงกันทุกฉบับ',
      text: 'ข้อมูลใน Invoice, Packing List และ Bill of Lading ต้องตรงกัน (ชื่อ, จำนวน, มูลค่า) หากไม่ตรงอาจถูกกักสินค้า',
    },
  ],
  // Country-specific warnings
  country: {
    CN: [
      {
        type: 'important',
        icon: 'flag',
        title: 'สิทธิ FTA กับจีน (ACFTA)',
        text: 'สินค้าจากจีนอาจได้สิทธิลดหย่อนภาษีภายใต้ ASEAN-China FTA (ACFTA) ต้องมี Certificate of Origin Form E',
      },
      {
        type: 'info',
        icon: 'alert-triangle',
        title: 'ระวังสินค้าไม่ได้มาตรฐาน',
        text: 'สินค้าจากจีนบางรายการอาจไม่ผ่านมาตรฐาน มอก. ควรขอใบรับรองคุณภาพจากผู้ผลิตก่อนสั่งซื้อ',
      },
    ],
    JP: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA กับญี่ปุ่น (JTEPA)',
        text: 'สินค้าจากญี่ปุ่นอาจได้สิทธิลดหย่อนภาษีภายใต้ Japan-Thailand Economic Partnership Agreement (JTEPA)',
      },
    ],
    US: [
      {
        type: 'important',
        icon: 'flag',
        title: 'ไม่มี FTA กับสหรัฐฯ',
        text: 'ไทยไม่มีข้อตกลง FTA กับสหรัฐอเมริกา สินค้าจะเสียภาษีในอัตราปกติ (MFN Rate)',
      },
      {
        type: 'info',
        icon: 'package',
        title: 'มาตรฐาน FDA สำหรับอาหาร/ยา',
        text: 'หากส่งออกอาหาร/ยาไปสหรัฐฯ ต้องผ่านมาตรฐาน US FDA ซึ่งมีข้อกำหนดเข้มงวด',
      },
    ],
    GB: [
      {
        type: 'info',
        icon: 'flag',
        title: 'กฎระเบียบหลัง Brexit',
        text: 'หลัง Brexit สหราชอาณาจักรมีกฎระเบียบนำเข้าแยกจาก EU ควรตรวจสอบข้อกำหนดล่าสุด',
      },
    ],
    VN: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA ภายใต้ AFTA/ATIGA',
        text: 'สินค้าจากเวียดนามได้สิทธิลดหย่อนภาษีภายใต้ ASEAN Trade in Goods Agreement (ATIGA)',
      },
    ],
    MY: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA ภายใต้ AFTA/ATIGA',
        text: 'สินค้าจากมาเลเซียได้สิทธิลดหย่อนภาษีภายใต้ ATIGA อัตราอากรส่วนใหญ่ 0%',
      },
    ],
    SG: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA ภายใต้ AFTA/ATIGA',
        text: 'สินค้าจากสิงคโปร์ได้สิทธิลดหย่อนภาษีภายใต้ ATIGA',
      },
    ],
    KR: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA กับเกาหลีใต้ (AKFTA)',
        text: 'สินค้าจากเกาหลีใต้อาจได้สิทธิลดหย่อนภาษีภายใต้ ASEAN-Korea FTA (AKFTA)',
      },
    ],
    DE: [
      {
        type: 'info',
        icon: 'flag',
        title: 'กฎระเบียบ EU',
        text: 'เยอรมนีเป็นสมาชิก EU สินค้าต้องเป็นไปตามมาตรฐาน CE Marking และกฎระเบียบ EU',
      },
    ],
  },
  // Product-category specific warnings
  product: {
    food: [
      {
        type: 'critical',
        icon: 'soup',
        title: 'ต้องขออนุญาต อย. ก่อนนำเข้าอาหาร',
        text: 'อาหารทุกประเภทต้องขอใบอนุญาตนำเข้าจาก อย. และต้องมีฉลากภาษาไทย รวมถึงแสดงวันผลิต/หมดอายุ',
      },
      {
        type: 'important',
        icon: 'tag',
        title: 'ฉลากภาษาไทยบังคับ',
        text: 'อาหารนำเข้าต้องมีฉลากภาษาไทยแสดงชื่อ, ส่วนประกอบ, วันผลิต, วันหมดอายุ, เลข อย.',
      },
    ],
    cosmetics: [
      {
        type: 'critical',
        icon: 'sparkles',
        title: 'ต้องจดแจ้งเครื่องสำอางกับ อย.',
        text: 'เครื่องสำอางทุกชนิดต้องจดแจ้งกับ อย. ก่อนจำหน่าย ต้องมีฉลากภาษาไทยและส่วนประกอบตาม INCI',
      },
      {
        type: 'important',
        icon: 'ban',
        title: 'ตรวจสอบสารต้องห้าม',
        text: 'เครื่องสำอางต้องไม่มีสารต้องห้ามตามประกาศ อย. เช่น ปรอท สเตียรอยด์ ไฮโดรควิโนน',
      },
    ],
    electronics: [
      {
        type: 'important',
        icon: 'smartphone',
        title: 'มาตรฐาน มอก. (TIS)',
        text: 'อุปกรณ์ไฟฟ้า/อิเล็กทรอนิกส์หลายรายการต้องมีมาตรฐาน มอก. เช่น สายชาร์จ อะแดปเตอร์ หม้อแปลง',
      },
      {
        type: 'info',
        icon: 'radio',
        title: 'อุปกรณ์ที่มีคลื่นวิทยุต้องขอ กสทช.',
        text: 'อุปกรณ์ที่ใช้คลื่นความถี่วิทยุ (Wi-Fi, Bluetooth, 5G) อาจต้องขอใบอนุญาตจาก กสทช.',
      },
    ],
    chemicals: [
      {
        type: 'critical',
        icon: 'flask-conical',
        title: 'สารเคมีอันตรายต้องขออนุญาต',
        text: 'สารเคมีอันตรายต้องขอใบอนุญาตจากกรมโรงงานอุตสาหกรรม และต้องมี MSDS (Material Safety Data Sheet)',
      },
    ],
    vehicles: [
      {
        type: 'critical',
        icon: 'car',
        title: 'อัตราภาษีสูงมาก',
        text: 'ยานพาหนะมีอัตราอากรขาเข้าสูงมาก (40-80%) และอาจมีภาษีสรรพสามิตเพิ่มเติม',
      },
      {
        type: 'important',
        icon: 'file-text',
        title: 'ต้องขอใบอนุญาตนำเข้า',
        text: 'การนำเข้ารถยนต์ต้องขอใบอนุญาตจากกระทรวงพาณิชย์ และต้องผ่านมาตรฐาน มอก.',
      },
    ],
    agriculture: [
      {
        type: 'critical',
        icon: 'sprout',
        title: 'ต้องมีใบรับรองสุขอนามัยพืช',
        text: 'สินค้าเกษตรต้องมี Phytosanitary Certificate จากประเทศต้นทาง และอาจต้องกักกันพืช',
      },
    ],
  },
};

// ---- FTA Information (simplified) ----
const FTA_INFO = {
  CN: { name: 'ACFTA (ASEAN-China FTA)', form: 'Form E' },
  JP: { name: 'JTEPA', form: 'Form JTEPA' },
  KR: { name: 'AKFTA (ASEAN-Korea FTA)', form: 'Form AK' },
  AU: { name: 'TAFTA (Thailand-Australia FTA)', form: 'Form TAFTA' },
  IN: { name: 'AIFTA (ASEAN-India FTA)', form: 'Form AI' },
  VN: { name: 'ATIGA (ASEAN)', form: 'Form D' },
  MY: { name: 'ATIGA (ASEAN)', form: 'Form D' },
  SG: { name: 'ATIGA (ASEAN)', form: 'Form D' },
  ID: { name: 'ATIGA (ASEAN)', form: 'Form D' },
  PH: { name: 'ATIGA (ASEAN)', form: 'Form D' },
};

// ---- Translation Dictionary ----
const TRANSLATIONS = {
  th: {
    // Categories
    "อาหารและเครื่องดื่ม": "อาหารและเครื่องดื่ม",
    "เครื่องสำอาง / ยา / เวชภัณฑ์": "เครื่องสำอาง / ยา / เวชภัณฑ์",
    "อิเล็กทรอนิกส์": "อิเล็กทรอนิกส์",
    "เสื้อผ้า / สิ่งทอ": "เสื้อผ้า / สิ่งทอ",
    "เครื่องจักร / อุปกรณ์": "เครื่องจักร / อุปกรณ์",
    "เคมีภัณฑ์": "เคมีภัณฑ์",
    "สินค้าเกษตร": "สินค้าเกษตร",
    "ยานพาหนะ / อะไหล่": "ยานพาหนะ / อะไหล่",
    "อัญมณี / เครื่องประดับ": "อัญมณี / เครื่องประดับ",
    "สินค้าทั่วไป": "สินค้าทั่วไป",

    // Static HTML labels/IDs
    "brand-sub": "Smart Trade Assistant",
    "hero-badge": "พร้อมใช้งานสำหรับประเทศไทย",
    "hero-title": "การค้าระหว่างประเทศ<br><span class=\"gradient-text\">เรื่องง่ายกว่าที่คิด</span>",
    "hero-subtitle": "ผู้ช่วยดิจิทัลสำหรับนักธุรกิจไทย นำทางคุณทุกขั้นตอน ตั้งแต่เช็คลิสต์นำเข้า-ส่งออก, คำนวณภาษี, ไปจนถึงตรวจสินค้าต้องห้าม — รวมไว้ในที่เดียว ไม่ต้องปวดหัวกับกฎระเบียบ",
    "start-btn": "<i class=\"inline-icon\" data-lucide=\"rocket\"></i> เริ่มต้นใช้งานฟรี",
    "learn-more": "<i class=\"inline-icon\" data-lucide=\"book-open\"></i> เรียนรู้เพิ่มเติม",
    "select-title": "<i class=\"inline-icon\" data-lucide=\"globe\"></i> เลือกลักษณะการค้า",
    "select-subtitle": "ระบุต้นทาง ปลายทาง และประเภทสินค้าของคุณ เพื่อรับคำแนะนำที่แม่นยำ",
    "import-btn": "นำเข้า (Import)",
    "export-btn": "ส่งออก (Export)",
    "origin-label": "ประเทศต้นทาง (Origin)",
    "origin-placeholder": "ค้นหาประเทศ เช่น จีน, US...",
    "dest-label": "ประเทศปลายทาง (Destination)",
    "dest-placeholder": "ค้นหาประเทศ เช่น ไทย, Japan...",
    "category-label": "หมวดหมู่สินค้าหลัก",
    "continue-btn": "ดำเนินการต่อ <i class=\"inline-icon\" data-lucide=\"arrow-right\"></i>",
    "nav-menu-title": "เมนูการใช้งาน",
    "checklist-card-title": "เช็คลิสต์ขั้นตอน",
    "checklist-card-desc": "รายการสิ่งที่ต้องทำ Step-by-step ตั้งแต่เริ่มจนรับสินค้า พร้อมเอกสารที่ต้องใช้",
    "calc-card-title": "คำนวณภาษีนำเข้า",
    "calc-card-desc": "คำนวณมูลค่า CIF, อากรขาเข้า และภาษีมูลค่าเพิ่ม (VAT 7%) ก่อนตัดสินใจ",
    "product-card-title": "ตรวจสินค้าต้องห้าม",
    "product-card-desc": "เช็คว่าสินค้าของคุณเป็นสินค้าต้องห้าม หรือต้องขอใบอนุญาตพิเศษหรือไม่",
    "warnings-card-title": "กฎระเบียบ & คำเตือน",
    "warnings-card-desc": "ตรวจสอบกฎหมาย, สิทธิ FTA, และข้อควรระวังสำคัญสำหรับสินค้านี้",
    "footer-disclaimer": "TradePilot AI &copy; 2026. สร้างเพื่อเป็นข้อมูลเบื้องต้นเท่านั้น ไม่ใช่คำแนะนำทางกฎหมาย.",
    "about-modal-title": "เกี่ยวกับ TradePilot AI",
    "about-desc": "<strong>TradePilot AI</strong> คือระบบผู้ช่วยอัจฉริยะที่พัฒนาขึ้นเพื่อสนับสนุนผู้ประกอบการและบุคคลทั่วไปที่สนใจในการทำธุรกิจนำเข้าและส่งออกสินค้าระหว่างประเทศ",
    "key-features-title": "<i class=\"inline-icon\" data-lucide=\"lightbulb\"></i> ฟีเจอร์หลักของเรา:",
    "feature-checklist": "<strong><i class=\"inline-icon\" data-lucide=\"clipboard-list\"></i> เช็คลิสต์ขั้นตอนการค้า:</strong> แนะนำขั้นตอนแบบทีละสเต็ป (Step-by-step) แยกตามประเภทสินค้าและประเทศคู่ค้า พร้อมระบุเอกสารที่จำเป็น",
    "feature-calculator": "<strong><i class=\"inline-icon\" data-lucide=\"calculator\"></i> คำนวณภาษีนำเข้า:</strong> คำนวณค่า CIF, อากรขาเข้าเบื้องต้น และภาษีมูลค่าเพิ่ม (VAT 7%) ช่วยวางแผนต้นทุน",
    "feature-product": "<strong><i class=\"inline-icon\" data-lucide=\"ban\"></i> ตรวจสินค้าต้องห้าม/จำกัด:</strong> ค้นหาประวัติสินค้าเพื่อดูว่าติดควบคุมศุลกากร หรือต้องขอใบอนุญาตพิเศษจากหน่วยงานใดหรือไม่",
    "feature-warning": "<strong><i class=\"inline-icon\" data-lucide=\"alert-triangle\"></i> กฎระเบียบและสิทธิพิเศษ (FTA):</strong> แจ้งเตือนข้อจำกัดทางกฎหมายเฉพาะประเทศ และแนะนำสิทธิลดหย่อนภาษี (เช่น Form E)",
    "about-disclaimer-title": "<i class=\"inline-icon\" data-lucide=\"shield-alert\"></i> ข้อจำกัดความรับผิดชอบ (Disclaimer):",
    "about-disclaimer-text": "ข้อมูลทั้งหมดในระบบนี้รวบรวมเพื่อวัตถุประสงค์ในการให้ความรู้และเป็นแนวทางเบื้องต้นเท่านั้น ไม่ใช่คำแนะนำทางกฎหมายอย่างเป็นทางการ การนำเข้าหรือส่งออกจริงอาจมีเงื่อนไข รายละเอียด และอัตราภาษีที่ต่างออกไปตามพิกัดศุลกากร (HS Code) และกฎระเบียบของแต่ละหน่วยงานในขณะนั้น โปรดตรวจสอบข้อมูลอย่างเป็นทางการกับทางกรมศุลกากรหรือหน่วยงานภาครัฐที่เกี่ยวข้องอีกครั้งก่อนดำเนินธุรกรรม",
    
    // Checklist panel
    "checklist-title": "เช็คลิสต์ขั้นตอน",
    "checklist-progress-label": "ความคืบหน้า",
    
    // Calculator panel
    "calc-title": "คำนวณภาษีนำเข้า",
    "calc-form-title": "<i class=\"inline-icon\" data-lucide=\"edit-3\"></i> กรอกข้อมูล",
    "calc-cost-label": "ราคาสินค้า (Cost)",
    "calc-insurance-label": "ค่าประกัน (Insurance)",
    "calc-freight-label": "ค่าขนส่ง (Freight)",
    "calc-duty-label": "อัตราอากรขาเข้า (กำหนดเอง)",
    "calc-btn-text": "<i class=\"inline-icon\" data-lucide=\"calculator\"></i> คำนวณภาษี",
    "calc-result-title": "<i class=\"inline-icon\" data-lucide=\"bar-chart-2\"></i> ผลการคำนวณ",
    "calc-placeholder": "กรอกข้อมูลแล้วกด \"คำนวณภาษี\"<br>เพื่อดูผลลัพธ์",
    "calc-note-title": "หมายเหตุ:",
    "calc-note-text": "การคำนวณนี้เป็นการประมาณการเบื้องต้น อัตราอากรจริงขึ้นอยู่กับพิกัดศุลกากร (HS Code) ของสินค้า สินค้าบางรายการอาจมีภาษีสรรพสามิตเพิ่มเติม กรุณาตรวจสอบกับกรมศุลกากรอีกครั้ง",
    "calc-error-cost": "กรุณากรอกราคาสินค้า",
    
    // Prohibited panel
    "prod-title": "ตรวจสินค้าต้องห้าม / จำกัด",
    "prod-search-placeholder": "🔍 พิมพ์ชื่อสินค้าที่ต้องการตรวจสอบ เช่น บุหรี่ไฟฟ้า, เครื่องสำอาง, สุรา...",
    "prod-search-btn": "ตรวจสอบ",
    "prod-quick-tags-label": "🏷️ ค้นหาด่วน:",
    "prod-not-found": "ไม่พบในรายการสินค้าต้องห้าม/จำกัด",
    "prod-not-found-desc-start": "สินค้า \"<strong>",
    "prod-not-found-desc-end": "</strong>\" ไม่อยู่ในรายการสินค้าต้องห้ามหรือสินค้าจำกัดที่เราบันทึกไว้ อย่างไรก็ตาม กรุณาตรวจสอบกับกรมศุลกากรอีกครั้งเพื่อความแน่ใจ เนื่องจากรายการนี้อาจไม่ครอบคลุมทุกรายการ",
    "prod-ref-label": "ข้อมูลอ้างอิง:",
    "prod-ref-text": "ข้อมูลสินค้าต้องห้ามและสินค้าจำกัดนี้รวบรวมจากกรมศุลกากร, อย., และหน่วยงานที่เกี่ยวข้อง กฎระเบียบอาจมีการเปลี่ยนแปลง กรุณาตรวจสอบกับหน่วยงานที่เกี่ยวข้องก่อนดำเนินการ",
    
    // Warnings panel
    "warn-title": "กฎระเบียบ & คำเตือน",
    "warn-tag-critical": "สำคัญมาก",
    "warn-tag-important": "ควรทราบ",
    "warn-tag-info": "ข้อมูล",
    "warn-no-warnings": "ไม่มีคำเตือนเพิ่มเติมสำหรับตัวเลือกนี้",
    "warn-summary-critical": "สำคัญมาก: ",
    "warn-summary-important": "ควรทราบ: ",
    "warn-summary-info": "ข้อมูล: ",

    // Swap / Navigation
    "swap-btn-title": "สลับประเทศ",
    "theme-btn-title": "สลับโหมดสี",
    "lang-btn-title": "เปลี่ยนภาษา / Switch Language",
    "btn-back-dashboard": "กลับไปที่แดชบอร์ด",

    // Autocomplete / Country Selector Helper
    "autocomplete-no-results": "ไม่พบรายชื่อประเทศ",
    
    // Dashboard context
    "dashboard-edit-btn": "แก้ไข",
    
    // Extra
    "แก้ไข": "แก้ไข",
    // Added dynamically
    "B/L or AWB": "ใบตราส่งสินค้า (B/L or AWB)",
    "Bill of Lading / Air Waybill": "ใบตราส่งสินค้า (B/L or AWB)",
    "Certificate of Analysis": "ใบรายงานผลวิเคราะห์ (COA)",
    "Certificate of Analysis (COA)": "ใบรายงานผลวิเคราะห์ (COA)",
    "Certificate of Origin": "หนังสือรับรองถิ่นกำเนิดสินค้า (CO)",
    "Certificate of Origin (CO)": "หนังสือรับรองถิ่นกำเนิดสินค้า (CO)",
    "Commercial Invoice": "ใบกำกับสินค้า (Commercial Invoice)",
    "Digital Certificate": "ใบรับรองอิเล็กทรอนิกส์ (Digital Certificate)",
    "GitHub Repository": "GitHub Repository",
    "HS Code": "พิกัดศุลกากร (HS Code)",
    "HS Code 8 หลัก": "พิกัดศุลกากร (HS Code 8 หลัก)",
    "Health Certificate": "ใบรับรองสุขอนามัย (Health Certificate)",
    "MSDS": "เอกสารข้อมูลความปลอดภัยสารเคมี (MSDS)",
    "Packing List": "ใบรายการบรรจุสินค้า (Packing List)",
    "Phytosanitary Certificate": "ใบรับรองสุขอนามัยพืช (Phytosanitary Certificate)",
    "กฎระเบียบประเทศปลายทาง": "กฎระเบียบประเทศปลายทาง",
    "กรมปศุสัตว์": "กรมปศุสัตว์",
    "กรมวิชาการเกษตร": "กรมวิชาการเกษตร",
    "กรมศิลปากร": "กรมศิลปากร",
    "กรมศุลกากร": "กรมศุลกากร",
    "กรมสรรพสามิต + กรมศุลกากร": "กรมสรรพสามิต + กรมศุลกากร",
    "การส่งออกพระพุทธรูปหรือโบราณวัตถุต้องขออนุญาตจากกรมศิลปากร พระพุทธรูปสูงเกิน 13 ซม. ต้องมีใบอนุญาต": "การส่งออกพระพุทธรูปหรือโบราณวัตถุต้องขออนุญาตจากกรมศิลปากร พระพุทธรูปสูงเกิน 13 ซม. ต้องมีใบอนุญาต",
    "ก่อนดำเนินการนำเข้าหรือส่งออก ต้องลงทะเบียนกับกรมศุลกากรและมี Digital Certificate เพื่อใช้ระบบ e-Customs": "ก่อนดำเนินการนำเข้าหรือส่งออก ต้องลงทะเบียนกับกรมศุลกากรและมี Digital Certificate เพื่อใช้ระบบ e-Customs",
    "ขอ CO จากกรมการค้าต่างประเทศ หรือหอการค้าไทย เพื่อให้ผู้ซื้อใช้สิทธิ FTA": "ขอ CO จากกรมการค้าต่างประเทศ หรือหอการค้าไทย เพื่อให้ผู้ซื้อใช้สิทธิ FTA",
    "ขอ Certificate of Origin (CO)": "ขอ Certificate of Origin (CO)",
    "ขอหนังสือรับรองแหล่งกำเนิดสินค้า (CO)": "ขอหนังสือรับรองแหล่งกำเนิดสินค้า (CO)",
    "ขอใบอนุญาตนำเข้าอาหาร (อย.)": "ขอใบอนุญาตนำเข้าอาหาร (อย.)",
    "ข้อมูลใน Invoice, Packing List และ Bill of Lading ต้องตรงกัน (ชื่อ, จำนวน, มูลค่า) หากไม่ตรงอาจถูกกักสินค้า": "ข้อมูลใน Invoice, Packing List และ Bill of Lading ต้องตรงกัน (ชื่อ, จำนวน, มูลค่า) หากไม่ตรงอาจถูกกักสินค้า",
    "จดแจ้งเครื่องสำอาง / ขออนุญาตยา": "จดแจ้งเครื่องสำอาง / ขออนุญาตยา",
    "จัดหา Freight Forwarder / Customs Broker": "จัดหา Freight Forwarder / Customs Broker",
    "จัดเตรียม Invoice, Packing List และเอกสารขนส่ง": "จัดเตรียม Invoice, Packing List และเอกสารขนส่ง",
    "จัดเตรียมเอกสารครบถ้วน": "จัดเตรียมเอกสารครบถ้วน",
    "จัดเตรียมเอกสารให้ครบถ้วน ข้อมูลต้องตรงกันทุกเอกสาร (ชื่อ, จำนวน, มูลค่า)": "จัดเตรียมเอกสารให้ครบถ้วน ข้อมูลต้องตรงกันทุกเอกสาร (ชื่อ, จำนวน, มูลค่า)",
    "ฉลากภาษาไทย": "ฉลากภาษาไทย",
    "ฉลากอาหาร (ภาษาไทย)": "ฉลากอาหาร (ภาษาไทย)",
    "ชำระอากรขาเข้า (อิเล็กทรอนิกส์มักอยู่ที่ 0-10%) + VAT 7%": "ชำระอากรขาเข้า (อิเล็กทรอนิกส์มักอยู่ที่ 0-10%) + VAT 7%",
    "ชำระอากรขาเข้า + VAT 7%": "ชำระอากรขาเข้า + VAT 7%",
    "ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment": "ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment",
    "ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment ของกรมศุลกากร": "ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment ของกรมศุลกากร",
    "ชำระอากรและภาษี": "ชำระอากรและภาษี",
    "ตรวจปล่อยสินค้าขาออก": "ตรวจปล่อยสินค้าขาออก",
    "ตรวจสอบ HS Code และข้อกำหนด มอก.": "ตรวจสอบ HS Code และข้อกำหนด มอก.",
    "ตรวจสอบกฎระเบียบของประเทศปลายทาง": "ตรวจสอบกฎระเบียบของประเทศปลายทาง",
    "ตรวจสอบจาก อย.": "ตรวจสอบจาก อย.",
    "ตรวจสอบจาก อย. ที่ด่านอาหารและยา": "ตรวจสอบจาก อย. ที่ด่านอาหารและยา",
    "ตรวจสอบพิกัดศุลกากร (HS Code)": "ตรวจสอบพิกัดศุลกากร (HS Code)",
    "ตรวจสอบว่าผลิตภัณฑ์ไม่มีสารต้องห้ามตามประกาศ อย.": "ตรวจสอบว่าผลิตภัณฑ์ไม่มีสารต้องห้ามตามประกาศ อย.",
    "ตรวจสอบว่าสินค้าต้องขอใบอนุญาตหรือไม่": "ตรวจสอบว่าสินค้าต้องขอใบอนุญาตหรือไม่",
    "ตรวจสอบว่าสินค้าเป็นสินค้าควบคุมส่งออกหรือไม่": "ตรวจสอบว่าสินค้าเป็นสินค้าควบคุมส่งออกหรือไม่",
    "ตรวจสอบสารต้องห้ามในส่วนผสม": "ตรวจสอบสารต้องห้ามในส่วนผสม",
    "ตั้งแต่ปี 2024 สินค้านำเข้าทุกรายการรวมถึงมูลค่าต่ำกว่า 1,500 บาท ต้องเสียภาษีมูลค่าเพิ่ม (VAT) 7%": "ตั้งแต่ปี 2024 สินค้านำเข้าทุกรายการรวมถึงมูลค่าต่ำกว่า 1,500 บาท ต้องเสียภาษีมูลค่าเพิ่ม (VAT) 7%",
    "ต้องขอใบอนุญาตจากนายทะเบียนอาวุธปืน สำนักงานตำรวจแห่งชาติ": "ต้องขอใบอนุญาตจากนายทะเบียนอาวุธปืน สำนักงานตำรวจแห่งชาติ",
    "ต้องขอใบอนุญาตนำเข้ายาจาก อย. ก่อนนำเข้า สำหรับใช้ส่วนตัวต้องมีใบรับรองแพทย์และนำเข้าได้ไม่เกิน 30 วัน": "ต้องขอใบอนุญาตนำเข้ายาจาก อย. ก่อนนำเข้า สำหรับใช้ส่วนตัวต้องมีใบรับรองแพทย์และนำเข้าได้ไม่เกิน 30 วัน",
    "ต้องขอใบอนุญาตนำเข้าอาหารจาก อย. ต้องมีฉลากภาษาไทย และผ่านการตรวจสอบคุณภาพ": "ต้องขอใบอนุญาตนำเข้าอาหารจาก อย. ต้องมีฉลากภาษาไทย และผ่านการตรวจสอบคุณภาพ",
    "ต้องขึ้นทะเบียนกับ CAAT และ กสทช. ก่อนใช้งาน น้ำหนักเกิน 2 กก. ต้องขอใบอนุญาตเพิ่มเติม": "ต้องขึ้นทะเบียนกับ CAAT และ กสทช. ก่อนใช้งาน น้ำหนักเกิน 2 กก. ต้องขอใบอนุญาตเพิ่มเติม",
    "ต้องจดแจ้งเครื่องสำอางกับ อย. ก่อนจำหน่าย ต้องมีฉลากภาษาไทยและไม่มีสารต้องห้าม": "ต้องจดแจ้งเครื่องสำอางกับ อย. ก่อนจำหน่าย ต้องมีฉลากภาษาไทยและไม่มีสารต้องห้าม",
    "ต้องมีใบรับรองสุขภาพสัตว์ (Health Certificate) จากประเทศต้นทาง และขอใบอนุญาตนำเข้าจากกรมปศุสัตว์": "ต้องมีใบรับรองสุขภาพสัตว์ (Health Certificate) จากประเทศต้นทาง และขอใบอนุญาตนำเข้าจากกรมปศุสัตว์",
    "ต้องมีใบรับรองสุขอนามัยพืช (Phytosanitary Certificate) จากประเทศต้นทาง และอาจต้องขออนุญาตนำเข้าจากกรมวิชาการเกษตร": "ต้องมีใบรับรองสุขอนามัยพืช (Phytosanitary Certificate) จากประเทศต้นทาง และอาจต้องขออนุญาตนำเข้าจากกรมวิชาการเกษตร",
    "ต้องลงทะเบียนเป็นผู้นำเข้า/ส่งออก": "ต้องลงทะเบียนเป็นผู้นำเข้า/ส่งออก",
    "นอกจากเอกสารปกติ ต้องมี Health Certificate และ Phytosanitary Certificate (สินค้าพืช)": "นอกจากเอกสารปกติ ต้องมี Health Certificate และ Phytosanitary Certificate (สินค้าพืช)",
    "นำสินค้าเข้าท่าเรือ/สนามบิน": "นำสินค้าเข้าท่าเรือ/สนามบิน",
    "นำสินค้าไปยังท่าเรือหรือสนามบินตามที่ระบุ พร้อมเอกสารประกอบ": "นำสินค้าไปยังท่าเรือหรือสนามบินตามที่ระบุ พร้อมเอกสารประกอบ",
    "นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 200 มวน หรือยาสูบ 250 กรัม": "นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 200 มวน หรือยาสูบ 250 กรัม",
    "นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาตจากกรมสรรพสามิต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 1 ลิตร (ปลอดอากร)": "นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาตจากกรมสรรพสามิต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 1 ลิตร (ปลอดอากร)",
    "บัตรประชาชน": "บัตรประชาชน",
    "บัตรประชาชน/หนังสือเดินทาง": "บัตรประชาชน/หนังสือเดินทาง",
    "บุหรี่ / ยาสูบ": "บุหรี่ / ยาสูบ",
    "บุหรี่ไฟฟ้า / Vape / IQOS": "บุหรี่ไฟฟ้า / Vape / IQOS",
    "ผลการตรวจสอบ": "ผลการตรวจสอบ",
    "ผลการตรวจสอบจาก อย.": "ผลการตรวจสอบจาก อย.",
    "ผลวิเคราะห์": "ผลวิเคราะห์",
    "ผลวิเคราะห์คุณภาพ": "ผลวิเคราะห์คุณภาพ",
    "พระพุทธรูป / โบราณวัตถุ / ศิลปวัตถุ": "พระพุทธรูป / โบราณวัตถุ / ศิลปวัตถุ",
    "พืช / เมล็ดพันธุ์ / ผลไม้สด": "พืช / เมล็ดพันธุ์ / ผลไม้สด",
    "ยา / เวชภัณฑ์ / อาหารเสริม": "ยา / เวชภัณฑ์ / อาหารเสริม",
    "ยาเสพติดให้โทษ": "ยาเสพติดให้โทษ",
    "ยื่นขออนุญาตนำเข้าอาหารจากสำนักงานคณะกรรมการอาหารและยา (อย.) ต้องขอก่อนนำเข้า": "ยื่นขออนุญาตนำเข้าอาหารจากสำนักงานคณะกรรมการอาหารและยา (อย.) ต้องขอก่อนนำเข้า",
    "ยื่นใบขนผ่านระบบ e-Customs": "ยื่นใบขนผ่านระบบ e-Customs",
    "ยื่นใบขนสินค้า (e-Import)": "ยื่นใบขนสินค้า (e-Import)",
    "ยื่นใบขนสินค้าขาออก (e-Export)": "ยื่นใบขนสินค้าขาออก (e-Export)",
    "ยื่นใบขนสินค้าขาเข้า (e-Import)": "ยื่นใบขนสินค้าขาเข้า (e-Import)",
    "ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร": "ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร",
    "ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร ระบบจะตรวจสอบข้อมูลอัตโนมัติ": "ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร ระบบจะตรวจสอบข้อมูลอัตโนมัติ",
    "ยื่นใบขนสินค้าผ่านระบบ e-Customs พร้อมแนบเอกสารประกอบ": "ยื่นใบขนสินค้าผ่านระบบ e-Customs พร้อมแนบเอกสารประกอบ",
    "รอการตรวจปล่อยจากศุลกากร (ส่วนใหญ่สินค้าส่งออกจะเข้า Green Line)": "รอการตรวจปล่อยจากศุลกากร (ส่วนใหญ่สินค้าส่งออกจะเข้า Green Line)",
    "รอตรวจปล่อยสินค้า": "รอตรวจปล่อยสินค้า",
    "รับสินค้า": "รับสินค้า",
    "รับสินค้าหลังผ่านการตรวจปล่อย": "รับสินค้าหลังผ่านการตรวจปล่อย",
    "รายการส่วนผสม (INCI)": "รายการส่วนผสม (INCI)",
    "ลงทะเบียนผู้นำเข้า": "ลงทะเบียนผู้นำเข้า",
    "ลงทะเบียนผู้ส่งออก": "ลงทะเบียนผู้ส่งออก",
    "ศึกษาข้อกำหนดการนำเข้าของประเทศปลายทาง เช่น มาตรฐาน, ฉลาก, ใบอนุญาต": "ศึกษาข้อกำหนดการนำเข้าของประเทศปลายทาง เช่น มาตรฐาน, ฉลาก, ใบอนุญาต",
    "สมัครเป็นผู้นำเข้ากับกรมศุลกากร": "สมัครเป็นผู้นำเข้ากับกรมศุลกากร",
    "สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate": "สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate",
    "สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs": "สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs",
    "สมัครเป็นผู้ส่งออกกับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs": "สมัครเป็นผู้ส่งออกกับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs",
    "สัญญาจ้างตัวแทน": "สัญญาจ้างตัวแทน",
    "สัตว์ป่าคุ้มครอง / ผลิตภัณฑ์จากสัตว์ป่า": "สัตว์ป่าคุ้มครอง / ผลิตภัณฑ์จากสัตว์ป่า",
    "สัตว์มีชีวิต / ผลิตภัณฑ์จากสัตว์": "สัตว์มีชีวิต / ผลิตภัณฑ์จากสัตว์",
    "สำนักงาน กสทช. (NBTC)": "สำนักงาน กสทช. (NBTC)",
    "สำนักงานการบินพลเรือนแห่งประเทศไทย (CAAT) + กสทช.": "สำนักงานการบินพลเรือนแห่งประเทศไทย (CAAT) + กสทช.",
    "สำนักงานคณะกรรมการอาหารและยา (อย.)": "สำนักงานคณะกรรมการอาหารและยา (อย.)",
    "สำนักงานตำรวจแห่งชาติ": "สำนักงานตำรวจแห่งชาติ",
    "สินค้าจะถูกจัดเข้า Green Line (ไม่ตรวจ) หรือ Red Line (ต้องตรวจ) ตามระดับความเสี่ยง": "สินค้าจะถูกจัดเข้า Green Line (ไม่ตรวจ) หรือ Red Line (ต้องตรวจ) ตามระดับความเสี่ยง",
    "สินค้าจะถูกตรวจสอบที่ด่านอาหารและยา": "สินค้าจะถูกตรวจสอบที่ด่านอาหารและยา",
    "สินค้าทุกรายการต้องเสียภาษี VAT 7%": "สินค้าทุกรายการต้องเสียภาษี VAT 7%",
    "สินค้าบางประเภทต้องขออนุญาตก่อนส่งออก เช่น ข้าว, น้ำตาล, อาวุธ, โบราณวัตถุ": "สินค้าบางประเภทต้องขออนุญาตก่อนส่งออก เช่น ข้าว, น้ำตาล, อาวุธ, โบราณวัตถุ",
    "สินค้าบางประเภทต้องขออนุญาตจากหน่วยงานที่เกี่ยวข้อง เช่น อย., กรมวิชาการเกษตร, สำนักงาน กสทช.": "สินค้าบางประเภทต้องขออนุญาตจากหน่วยงานที่เกี่ยวข้อง เช่น อย., กรมวิชาการเกษตร, สำนักงาน กสทช.",
    "สินค้าปลอม / ละเมิดทรัพย์สินทางปัญญา": "สินค้าปลอม / ละเมิดทรัพย์สินทางปัญญา",
    "สินค้าอาหารจะถูกตรวจสอบที่ด่านอาหารและยา ก่อนปล่อยออกจากท่าเรือ/สนามบิน": "สินค้าอาหารจะถูกตรวจสอบที่ด่านอาหารและยา ก่อนปล่อยออกจากท่าเรือ/สนามบิน",
    "สินค้าอิเล็กทรอนิกส์บางชนิดต้องมีมาตรฐาน มอก. (TIS) และอาจต้องขอใบอนุญาตจาก กสทช.": "สินค้าอิเล็กทรอนิกส์บางชนิดต้องมีมาตรฐาน มอก. (TIS) และอาจต้องขอใบอนุญาตจาก กสทช.",
    "สื่อลามกอนาจาร": "สื่อลามกอนาจาร",
    "สุรา / เครื่องดื่มแอลกอฮอล์": "สุรา / เครื่องดื่มแอลกอฮอล์",
    "หนังสือจดทะเบียนบริษัท": "หนังสือจดทะเบียนบริษัท",
    "หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี": "หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี",
    "หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี ต้องมี Certificate of Origin จากประเทศต้นทาง": "หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี ต้องมี Certificate of Origin จากประเทศต้นทาง",
    "หาพิกัดอัตราศุลกากร (HS Code) ของสินค้าที่ต้องการนำเข้า เพื่อทราบอัตราอากรและข้อกำหนด": "หาพิกัดอัตราศุลกากร (HS Code) ของสินค้าที่ต้องการนำเข้า เพื่อทราบอัตราอากรและข้อกำหนด",
    "หาพิกัดอัตราศุลกากรของสินค้าอาหาร อัตราอากรอาหารมักอยู่ที่ 30-50%": "หาพิกัดอัตราศุลกากรของสินค้าอาหาร อัตราอากรอาหารมักอยู่ที่ 30-50%",
    "ห้ามนำเข้า ขาย และครอบครองในประเทศไทย ตามคำสั่งคณะกรรมการคุ้มครองผู้บริโภค มีโทษจำคุกสูงสุด 5 ปี หรือปรับสูงสุด 500,000 บาท": "ห้ามนำเข้า ขาย และครอบครองในประเทศไทย ตามคำสั่งคณะกรรมการคุ้มครองผู้บริโภค มีโทษจำคุกสูงสุด 5 ปี หรือปรับสูงสุด 500,000 บาท",
    "ห้ามนำเข้า-ส่งออกสัตว์ป่าและผลิตภัณฑ์จากสัตว์ป่าที่อยู่ในบัญชี CITES ตามพระราชบัญญัติสงวนและคุ้มครองสัตว์ป่า": "ห้ามนำเข้า-ส่งออกสัตว์ป่าและผลิตภัณฑ์จากสัตว์ป่าที่อยู่ในบัญชี CITES ตามพระราชบัญญัติสงวนและคุ้มครองสัตว์ป่า",
    "ห้ามนำเข้าสินค้าที่ละเมิดลิขสิทธิ์ เครื่องหมายการค้า หรือสิทธิบัตร มีโทษจำคุกและปรับ": "ห้ามนำเข้าสินค้าที่ละเมิดลิขสิทธิ์ เครื่องหมายการค้า หรือสิทธิบัตร มีโทษจำคุกและปรับ",
    "ห้ามนำเข้าสิ่งพิมพ์ ภาพ หรือสื่อลามกอนาจารทุกรูปแบบ": "ห้ามนำเข้าสิ่งพิมพ์ ภาพ หรือสื่อลามกอนาจารทุกรูปแบบ",
    "ห้ามนำเข้าเงินตราปลอม เหรียญปลอม หรือดวงตราปลอมของรัฐบาลโดยเด็ดขาด": "ห้ามนำเข้าเงินตราปลอม เหรียญปลอม หรือดวงตราปลอมของรัฐบาลโดยเด็ดขาด",
    "ห้ามนำเข้าและส่งออกโดยเด็ดขาด ตามพระราชบัญญัติยาเสพติดให้โทษ ผู้ฝ่าฝืนมีโทษจำคุกสูงสุดตลอดชีวิตหรือประหารชีวิต": "ห้ามนำเข้าและส่งออกโดยเด็ดขาด ตามพระราชบัญญัติยาเสพติดให้โทษ ผู้ฝ่าฝืนมีโทษจำคุกสูงสุดตลอดชีวิตหรือประหารชีวิต",
    "อาวุธปืน / กระสุน / วัตถุระเบิด": "อาวุธปืน / กระสุน / วัตถุระเบิด",
    "อาหาร / อาหารแปรรูป": "อาหาร / อาหารแปรรูป",
    "อิเล็กทรอนิกส์หลายรายการได้สิทธิ FTA อัตราอากร 0%": "อิเล็กทรอนิกส์หลายรายการได้สิทธิ FTA อัตราอากร 0%",
    "อุปกรณ์โทรคมนาคม / วิทยุสื่อสาร": "อุปกรณ์โทรคมนาคม / วิทยุสื่อสาร",
    "เครื่องวิทยุคมนาคมต้องขอใบอนุญาตจาก กสทช. ก่อนนำเข้า": "เครื่องวิทยุคมนาคมต้องขอใบอนุญาตจาก กสทช. ก่อนนำเข้า",
    "เครื่องสำอาง": "เครื่องสำอาง",
    "เครื่องสำอางต้องจดแจ้งกับ อย. ก่อนนำเข้า ยาต้องขอใบอนุญาตนำเข้ายาแผนปัจจุบัน": "เครื่องสำอางต้องจดแจ้งกับ อย. ก่อนนำเข้า ยาต้องขอใบอนุญาตนำเข้ายาแผนปัจจุบัน",
    "เงินตราปลอม / ตราปลอม": "เงินตราปลอม / ตราปลอม",
    "เตรียมเอกสารการค้า": "เตรียมเอกสารการค้า",
    "เตรียมเอกสารการค้า + ใบรับรองสุขอนามัย": "เตรียมเอกสารการค้า + ใบรับรองสุขอนามัย",
    "เมื่อผ่านการตรวจปล่อยจากศุลกากรและ อย. แล้ว สามารถรับสินค้าได้": "เมื่อผ่านการตรวจปล่อยจากศุลกากรและ อย. แล้ว สามารถรับสินค้าได้",
    "เมื่อผ่านการตรวจปล่อยแล้ว สามารถรับสินค้าจากท่าเรือ/สนามบินได้": "เมื่อผ่านการตรวจปล่อยแล้ว สามารถรับสินค้าจากท่าเรือ/สนามบินได้",
    "เอกสารต้องตรงกันทุกฉบับ": "เอกสารต้องตรงกันทุกฉบับ",
    "แนะนำให้ใช้ตัวแทนออกของ (Customs Broker) ที่มีใบอนุญาตเพื่อดำเนินพิธีการศุลกากร": "แนะนำให้ใช้ตัวแทนออกของ (Customs Broker) ที่มีใบอนุญาตเพื่อดำเนินพิธีการศุลกากร",
    "โดรน / อากาศยานไร้คนขับ": "โดรน / อากาศยานไร้คนขับ",
    "ใบขนสินค้า": "ใบขนสินค้า",
    "ใบขนสินค้า (Customs Declaration)": "ใบขนสินค้า (Customs Declaration)",
    "ใบขนสินค้าขาออก": "ใบขนสินค้าขาออก",
    "ใบขึ้นทะเบียน CAAT": "ใบขึ้นทะเบียน CAAT",
    "ใบจดแจ้งเครื่องสำอาง": "ใบจดแจ้งเครื่องสำอาง",
    "ใบจดแจ้งเครื่องสำอาง / ใบอนุญาตนำเข้ายา": "ใบจดแจ้งเครื่องสำอาง / ใบอนุญาตนำเข้ายา",
    "ใบปล่อยสินค้า": "ใบปล่อยสินค้า",
    "ใบปล่อยสินค้า (Delivery Order)": "ใบปล่อยสินค้า (Delivery Order)",
    "ใบรับรอง มอก. (ถ้ามี)": "ใบรับรอง มอก. (ถ้ามี)",
    "ใบรับรองการฉีดวัคซีน": "ใบรับรองการฉีดวัคซีน",
    "ใบรับรองแพทย์ (กรณีส่วนตัว)": "ใบรับรองแพทย์ (กรณีส่วนตัว)",
    "ใบอนุญาต กสทช.": "ใบอนุญาต กสทช.",
    "ใบอนุญาต กสทช. (ถ้ามี)": "ใบอนุญาต กสทช. (ถ้ามี)",
    "ใบอนุญาตขาย": "ใบอนุญาตขาย",
    "ใบอนุญาตจากกรมศิลปากร": "ใบอนุญาตจากกรมศิลปากร",
    "ใบอนุญาตนำเข้า": "ใบอนุญาตนำเข้า",
    "ใบอนุญาตนำเข้า (ถ้ามี)": "ใบอนุญาตนำเข้า (ถ้ามี)",
    "ใบอนุญาตนำเข้า (บางชนิด)": "ใบอนุญาตนำเข้า (บางชนิด)",
    "ใบอนุญาตนำเข้ายา": "ใบอนุญาตนำเข้ายา",
    "ใบอนุญาตนำเข้าสัตว์": "ใบอนุญาตนำเข้าสัตว์",
    "ใบอนุญาตนำเข้าอาวุธปืน": "ใบอนุญาตนำเข้าอาวุธปืน",
    "ใบอนุญาตนำเข้าอาหาร": "ใบอนุญาตนำเข้าอาหาร",
    "ใบอนุญาตนำเข้าเครื่องวิทยุคมนาคม": "ใบอนุญาตนำเข้าเครื่องวิทยุคมนาคม",
    "ใบอนุญาตส่งออก (ถ้ามี)": "ใบอนุญาตส่งออก (ถ้ามี)",
    "ใบเสร็จ": "ใบเสร็จ",
    "ใบเสร็จ VAT": "ใบเสร็จ VAT",
    "ใบเสร็จชำระอากร": "ใบเสร็จชำระอากร",

  },
  en: {
    // Categories
    "อาหารและเครื่องดื่ม": "Food & Beverages",
    "เครื่องสำอาง / ยา / เวชภัณฑ์": "Cosmetics / Medicine / Pharmaceuticals",
    "อิเล็กทรอนิกส์": "Electronics",
    "เสื้อผ้า / สิ่งทอ": "Textiles / Clothing",
    "เครื่องจักร / อุปกรณ์": "Machinery / Equipment",
    "เคมีภัณฑ์": "Chemicals",
    "สินค้าเกษตร": "Agricultural Products",
    "ยานพาหนะ / อะไหล่": "Vehicles & Parts",
    "อัญมณี / เครื่องประดับ": "Jewelry & Accessories",
    "สินค้าทั่วไป": "General Goods",

    // Static HTML labels/IDs
    "hero-badge": "Ready for Thailand",
    "hero-title": "International Trade<br><span class=\"gradient-text\">Easier than you think</span>",
    "hero-subtitle": "Digital assistant for Thai entrepreneurs, guiding you through every step. From import-export checklists, tax calculations, to checking prohibited goods — all in one place, no more regulatory headaches.",
    "start-btn": "<i class=\"inline-icon\" data-lucide=\"rocket\"></i> Start for Free",
    "learn-more": "<i class=\"inline-icon\" data-lucide=\"book-open\"></i> Learn More",
    "select-title": "<i class=\"inline-icon\" data-lucide=\"globe\"></i> Select Trade Type",
    "select-subtitle": "Specify origin, destination, and product category for accurate guidance",
    "import-btn": "Import",
    "export-btn": "Export",
    "origin-label": "Origin Country",
    "origin-placeholder": "Search country e.g. China, US...",
    "dest-label": "Destination Country",
    "dest-placeholder": "Search country e.g. Thailand, Japan...",
    "category-label": "Main Product Category",
    "continue-btn": "Continue <i class=\"inline-icon\" data-lucide=\"arrow-right\"></i>",
    "nav-menu-title": "Navigation Menu",
    "checklist-card-title": "Process Checklist",
    "checklist-card-desc": "Step-by-step to-do list from start to delivery, with required documents",
    "calc-card-title": "Import Tax Calculator",
    "calc-card-desc": "Calculate CIF value, import duty, and value-added tax (VAT 7%) before deciding",
    "product-card-title": "Check Prohibited Goods",
    "product-card-desc": "Check if your items are prohibited or require special permits",
    "warnings-card-title": "Regulations & Warnings",
    "warnings-card-desc": "Verify laws, FTA benefits, and critical precautions for this product",
    "footer-disclaimer": "TradePilot AI &copy; 2026. Created for informational purposes only, not legal advice.",
    "about-modal-title": "About TradePilot AI",
    "about-desc": "<strong>TradePilot AI</strong> is a smart assistant system developed to support entrepreneurs and individuals interested in international import and export business.",
    "key-features-title": "<i class=\"inline-icon\" data-lucide=\"lightbulb\"></i> Our Key Features:",
    "feature-checklist": "<strong><i class=\"inline-icon\" data-lucide=\"clipboard-list\"></i> Process Checklist:</strong> Step-by-step guidance customized by product category and trading countries, along with required documents.",
    "feature-calculator": "<strong><i class=\"inline-icon\" data-lucide=\"calculator\"></i> Import Tax Calculator:</strong> Estimates CIF value, import duty, and VAT (7%) to help plan your costs.",
    "feature-product": "<strong><i class=\"inline-icon\" data-lucide=\"ban\"></i> Prohibited/Restricted Goods Check:</strong> Search goods to see if they are controlled by customs or require special permits from any agency.",
    "feature-warning": "<strong><i class=\"inline-icon\" data-lucide=\"alert-triangle\"></i> Regulations & FTA Benefits:</strong> Alert country-specific legal restrictions and suggest tax reduction privileges (e.g. Form E).",
    "about-disclaimer-title": "<i class=\"inline-icon\" data-lucide=\"shield-alert\"></i> Disclaimer:",
    "about-disclaimer-text": "All information in this system is compiled for educational and preliminary guidance purposes only, not official legal advice. Actual imports or exports may have different conditions, details, and tax rates based on HS Codes and regulations of each agency at the time. Please verify official information with the Customs Department or relevant government agencies before conducting transactions.",
    
    // Checklist panel
    "checklist-title": "Process Checklist",
    "checklist-progress-label": "Progress",
    
    // Calculator panel
    "calc-title": "Import Tax Calculator",
    "calc-form-title": "<i class=\"inline-icon\" data-lucide=\"edit-3\"></i> Enter Data",
    "calc-cost-label": "Cost of Goods",
    "calc-insurance-label": "Insurance",
    "calc-freight-label": "Freight",
    "calc-duty-label": "Import Duty Rate (Custom)",
    "calc-btn-text": "<i class=\"inline-icon\" data-lucide=\"calculator\"></i> Calculate Tax",
    "calc-result-title": "<i class=\"inline-icon\" data-lucide=\"bar-chart-2\"></i> Calculation Result",
    "calc-placeholder": "Fill in the fields and click \"Calculate Tax\" <br>to see the breakdown.",
    "calc-note-title": "Note:",
    "calc-note-text": "This calculation is a preliminary estimate. The actual duty rate depends on the specific HS Code. Some items may be subject to additional excise taxes. Please verify with the Customs Department.",
    "calc-error-cost": "Please enter the cost of goods.",
    
    // Prohibited panel
    "prod-title": "Check Prohibited/Restricted Goods",
    "prod-search-placeholder": "🔍 Type product name to check, e.g. e-cigarette, cosmetics, liquor...",
    "prod-search-btn": "Check",
    "prod-quick-tags-label": "🏷️ Quick Search:",
    "prod-not-found": "Not found in prohibited/restricted lists",
    "prod-not-found-desc-start": "Product \"<strong>",
    "prod-not-found-desc-end": "</strong>\" is not in our database of prohibited or restricted goods. However, please verify with the Customs Department as this list may not cover all regulated products.",
    "prod-ref-label": "References:",
    "prod-ref-text": "Prohibited and restricted items database compiled from the Customs Department, FDA, and relevant agencies. Regulations are subject to change. Please verify before proceeding.",
    
    // Warnings panel
    "warn-title": "Regulations & Warnings",
    "warn-tag-critical": "Critical",
    "warn-tag-important": "Important",
    "warn-tag-info": "Info",
    "warn-no-warnings": "No additional warnings for this selection",
    "warn-summary-critical": "Critical: ",
    "warn-summary-important": "Important: ",
    "warn-summary-info": "Info: ",

    // Swap / Navigation
    "swap-btn-title": "Swap Countries",
    "theme-btn-title": "Toggle Theme",
    "lang-btn-title": "Switch Language",
    "btn-back-dashboard": "Back to Dashboard",

    // Autocomplete / Country Selector Helper
    "autocomplete-no-results": "No countries found",
    
    // Dashboard context
    "dashboard-edit-btn": "Edit",
    "import": "Import",
    "export": "Export",
    "การนำเข้า": "Import",
    "การส่งออก": "Export",

    // Dynamic warning and sanctions messages
    "เส้นทางการค้าไม่ถูกต้อง": "Invalid Trade Route",
    "ประเทศต้นทางและปลายทางไม่สามารถเป็นประเทศเดียวกันได้สำหรับการค้าระหว่างประเทศ กรุณาเลือกประเทศใหม่": "Origin and destination countries cannot be the same for international trade. Please select a different country.",
    "เส้นทางการค้าถูกระงับ (Trade Embargo)": "Trade Embargo in Place",
    "ประเทศเกาหลีเหนือ (North Korea) อยู่ภายใต้มาตรการคว่ำบาตรทางการค้าอย่างเข้มงวดจากองค์การสหประชาชาติ (UN Sanctions) ทำให้ไม่สามารถดำเนินพิธีการนำเข้า/ส่งออกเชิงพาณิชย์ทั่วไปได้": "North Korea (KP) is under strict UN trade sanctions. Standard commercial imports/exports are not permitted.",
    "เส้นทางการค้ามีข้อจำกัดร้ายแรง (Sanctioned Route)": "Sanctioned Trade Route",
    "ประเทศอิหร่าน (Iran) อยู่ภายใต้ข้อจำกัดทางการเงินและการค้าของระบบระหว่างประเทศ ห้ามทำธุรกรรมการค้าหรือการขนส่งในสินค้ากลุ่มเทคโนโลยี พลังงาน และอุปกรณ์อุตสาหกรรม": "Iran (IR) is under international financial and trade sanctions. Transactions or shipping of tech, energy, and industrial goods are prohibited.",
    "เส้นทางการค้าถูกระงับ (Restricted Route)": "Restricted Trade Route",
    "ประเทศซีเรีย (Syria) อยู่ภายใต้มาตรการคว่ำบาตรระดับสากลอันเนื่องจากปัญหาความมั่นคง ไม่สามารถนำเข้าหรือส่งออกสินค้าระหว่างประเทศในเชิงพาณิชย์ปกติได้": "Syria (SY) is under international security sanctions. Commercial import/export operations are suspended.",
    "ข้อจำกัดการคว่ำบาตรทางการค้า (US-Cuba Embargo)": "US-Cuba Trade Embargo",
    "มีการคว่ำบาตรทางการค้าระหว่างสหรัฐอเมริกาและคิวบาอย่างเข้มงวด (US Embargo on Cuba) ห้ามเรือสินค้าหรือสายการบินดำเนินพิธีการค้าระหว่างสองประเทศนี้โดยตรง": "Direct trade between the United States and Cuba is strictly prohibited under the US embargo. Shipping vessels or airlines cannot route directly.",
    "เส้นทางการค้าระหว่างประเทศถูกระงับเนื่องจากสงคราม": "Trade Route Suspended Due to Conflict",
    "การทำธุรกรรมและการขนส่งสินค้าระหว่างประเทศยูเครนและสหพันธรัฐรัสเซียถูกระงับโดยสิ้นเชิงเนื่องจากภาวะความขัดแย้งด้านความมั่นคง": "International transactions and shipping between Ukraine and the Russian Federation are suspended due to geopolitical conflict.",
    "คู่ค้านอกประเทศไทย (เส้นทางการค้าทั่วไป)": "Non-Thailand Trade Route",
    "ระบบนี้วิเคราะห์ข้อมูลอ้างอิงพิกัดและอัตราอากรศุลกากรของประเทศไทยเป็นหลัก เช็คลิสต์และข้อมูลคำนวณสำหรับคู่ค้านอกประเทศจะเป็นรูปแบบมาตรฐานทั่วไป ซึ่งอาจแตกต่างจากกฎหมายท้องถิ่นของประเทศนั้นๆ": "This system mainly reference customs codes and duty rates for Thailand. Checklists and tax calculations for routes not involving Thailand will use global standards which may differ from local regulations.",

    // Calculator results
    "ราคาสินค้า (Cost)": "Cost of Goods",
    "ค่าประกัน (Insurance)": "Insurance",
    "ค่าขนส่ง (Freight)": "Freight",
    "มูลค่า CIF": "CIF Value",
    "อากรขาเข้า": "Import Duty",
    "ฐานภาษี VAT (CIF + อากร)": "VAT Base (CIF + Duty)",
    "VAT (7%)": "VAT (7%)",
    "ภาษีรวม (อากร + VAT)": "Total Tax (Duty + VAT)",
    "ต้นทุนทั้งหมด (CIF + ภาษี)": "Total Cost (CIF + Tax)",

    // Quick search tags translations (both directions)
    "บุหรี่ไฟฟ้า": "E-cigarette",
    "เครื่องสำอาง": "Cosmetics",
    "อาหารเสริม": "Supplements",
    "ยา": "Medicine",
    "สุรา": "Liquor",
    "โดรน": "Drones",
    "สัตว์เลี้ยง": "Pets",
    "พืช": "Plants",
    "อาวุธ": "Weapons",
    "ของก๊อป": "Counterfeits",
    "พระพุทธรูป": "Buddha Images",
    "ผลไม้": "Fruits",
    "สารเคมี": "Chemicals",

    // Prohibited/Restricted database translations
    "ยาเสพติดให้โทษ": "Narcotics / Dangerous Drugs",
    "บุหรี่ไฟฟ้า / Vape / IQOS": "Electronic Cigarettes / Vape / IQOS",
    "สื่อลามกอนาจาร": "Obscene Materials / Pornography",
    "สินค้าปลอม / ละเมิดทรัพย์สินทางปัญญา": "Counterfeit Goods / Intellectual Property Infringement",
    "สัตว์ป่าคุ้มครอง / ผลิตภัณฑ์จากสัตว์ป่า": "Protected Wildlife / Wildlife Products",
    "เงินตราปลอม / ตราปลอม": "Counterfeit Currency / Fake Seals",
    "ยา / เวชภัณฑ์ / อาหารเสริม": "Medicine / Pharmaceuticals / Supplements",
    "เครื่องสำอาง": "Cosmetics",
    "อาวุธปืน / กระสุน / วัตถุระเบิด": "Firearms / Ammunition / Explosives",
    "พืช / เมล็ดพันธุ์ / ผลไม้สด": "Plants / Seeds / Fresh Fruits",
    "สัตว์มีชีวิต / ผลิตภัณฑ์จากสัตว์": "Live Animals / Animal Products",
    "พระพุทธรูป / โบราณวัตถุ / ศิลปวัตถุ": "Buddha Images / Antiques / Art Objects",
    "อุปกรณ์โทรคมนาคม / วิทยุสื่อสาร": "Telecommunications Equipment / Radio Transceivers",
    "โดรน / อากาศยานไร้คนขับ": "Drones / Unmanned Aerial Vehicles (UAV)",
    "สุรา / เครื่องดื่มแอลกอฮอล์": "Liquor / Alcoholic Beverages",
    "บุหรี่ / ยาสูบ": "Cigarettes / Tobacco",
    "อาหาร / อาหารแปรรูป": "Food / Processed Food",

    "ห้ามนำเข้า — ": "Prohibited Import — ",
    "ต้องมีใบอนุญาต — ": "Permit Required — ",
    "หน่วยงาน: ": "Agency: ",
    "เอกสารที่ต้องใช้: ": "Required Documents: ",

    // Warnings data translations
    "ต้องลงทะเบียนเป็นผู้นำเข้า/ส่งออก": "Must Register as Importer/Exporter",
    "ก่อนดำเนินการนำเข้าหรือส่งออก ต้องลงทะเบียนกับกรมศุลกากรและมี Digital Certificate เพื่อใช้ระบบ e-Customs": "Before importing or exporting, you must register with the Customs Department and obtain a Digital Certificate to use the e-Customs system.",
    "สินค้าทุกรายการต้องเสียภาษี VAT 7%": "All Imported Goods Subject to 7% VAT",
    "ตั้งแต่ปี 2024 สินค้านำเข้าทุกรายการรวมถึงมูลค่าต่ำกว่า 1,500 บาท ต้องเสียภาษีมูลค่าเพิ่ม (VAT) 7%": "Since 2024, all imported items, including those valued under 1,500 THB, are subject to 7% Value Added Tax (VAT).",
    "เอกสารต้องตรงกันทุกฉบับ": "Documents Must Match Exactly",
    "ข้อมูลใน Invoice, Packing List และ Bill of Lading ต้องตรงกัน (ชื่อ, จำนวน, มูลค่า) หากไม่ตรงอาจถูกกักสินค้า": "Information in the Invoice, Packing List, and Bill of Lading must match (name, quantity, value). Discrepancies may lead to cargo detention.",
    "สิทธิ FTA กับจีน (ACFTA)": "FTA Benefits with China (ACFTA)",
    "สินค้าจากจีนอาจได้สิทธิลดหย่อนภาษีภายใต้ ASEAN-China FTA (ACFTA) ต้องมี Certificate of Origin Form E": "Goods from China may qualify for duty reduction under ASEAN-China FTA (ACFTA). Certificate of Origin Form E is required.",
    "ระวังสินค้าไม่ได้มาตรฐาน": "Beware of Substandard Goods",
    "สินค้าจากจีนบางรายการอาจไม่ผ่านมาตรฐาน มอก. ควรขอใบรับรองคุณภาพจากผู้ผลิตก่อนสั่งซื้อ": "Some Chinese products may not pass Thai Industrial Standards (TIS). Request a quality certificate from the manufacturer before ordering.",
    "สิทธิ FTA กับญี่ปุ่น (JTEPA)": "FTA Benefits with Japan (JTEPA)",
    "สินค้าจากญี่ปุ่นอาจได้สิทธิลดหย่อนภาษีภายใต้ Japan-Thailand Economic Partnership Agreement (JTEPA)": "Goods from Japan may qualify for duty reductions under the Japan-Thailand Economic Partnership Agreement (JTEPA).",
    "ไม่มี FTA กับสหรัฐฯ": "No FTA with the United States",
    "ไทยไม่มีข้อตกลง FTA กับสหรัฐอเมริกา สินค้าจะเสียภาษีในอัตราปกติ (MFN Rate)": "Thailand has no FTA with the US. Goods will be subject to normal tariff rates (MFN Rate).",
    "มาตรฐาน FDA สำหรับอาหาร/ยา": "FDA Standards for Food/Drugs",
    "หากส่งออกอาหาร/ยาไปสหรัฐฯ ต้องผ่านมาตรฐาน US FDA ซึ่งมีข้อกำหนดเข้มงวด": "If exporting food/drugs to the US, they must comply with strict US FDA regulations.",
    "กฎระเบียบหลัง Brexit": "Post-Brexit Regulations",
    "หลัง Brexit สหราชอาณาจักรมีกฎระเบียบนำเข้าแยกจาก EU ควรตรวจสอบข้อกำหนดล่าสุด": "Post-Brexit, the United Kingdom enforces import regulations separate from the EU. Check the latest requirements.",
    "สิทธิ FTA ภายใต้ AFTA/ATIGA": "FTA Benefits under AFTA/ATIGA",
    "สินค้าจากเวียดนามได้สิทธิลดหย่อนภาษีภายใต้ ASEAN Trade in Goods Agreement (ATIGA)": "Goods from Vietnam qualify for duty reduction under the ASEAN Trade in Goods Agreement (ATIGA).",
    "สินค้าจากมาเลเซียได้สิทธิลดหย่อนภาษีภายใต้ ATIGA อัตราอากรส่วนใหญ่ 0%": "Goods from Malaysia qualify for duty reduction under ATIGA. Most duties are 0%.",
    "สินค้าจากสิงคโปร์ได้สิทธิลดหย่อนภาษีภายใต้ ATIGA": "Goods from Singapore qualify for duty reduction under ATIGA.",
    "สิทธิ FTA กับเกาหลีใต้ (AKFTA)": "FTA Benefits with South Korea (AKFTA)",
    "สินค้าจากเกาหลีใต้อาจได้สิทธิลดหย่อนภาษีภายใต้ ASEAN-Korea FTA (AKFTA)": "Goods from South Korea may qualify for duty reduction under the ASEAN-Korea FTA (AKFTA).",
    "กฎระเบียบ EU": "EU Regulations",
    "เยอรมนีเป็นสมาชิก EU สินค้าต้องเป็นไปตามมาตรฐาน CE Marking และกฎระเบียบ EU": "Germany is an EU member. Goods must comply with CE Marking standards and EU regulations.",
    "ต้องขออนุญาต อย. ก่อนนำเข้าอาหาร": "Must Obtain FDA License before Importing Food",
    "อาหารทุกประเภทต้องขอใบอนุญาตนำเข้าจาก อย. และต้องมีฉลากภาษาไทย รวมถึงแสดงวันผลิต/หมดอายุ": "All food types require an import license from the FDA, and must bear Thai labeling showing manufacturing/expiration dates.",
    "ฉลากภาษาไทยบังคับ": "Mandatory Thai Labeling",
    "อาหารนำเข้าต้องมีฉลากภาษาไทยแสดงชื่อ, ส่วนประกอบ, วันผลิต, วันหมดอายุ, เลข อย.": "Imported food must have a Thai label showing product name, ingredients, mfg/exp dates, and FDA registration number.",
    "ต้องจดแจ้งเครื่องสำอางกับ อย.": "Must Register Cosmetics with the FDA",
    "เครื่องสำอางทุกชนิดต้องจดแจ้งกับ อย. ก่อนจำหน่าย ต้องมีฉลากภาษาไทยและส่วนประกอบตาม INCI": "All cosmetics must be registered with the FDA before sale, featuring Thai labels and ingredients listed per INCI.",
    "ตรวจสอบสารต้องห้าม": "Check for Prohibited Substances",
    "เครื่องสำอางต้องไม่มีสารต้องห้ามตามประกาศ อย. เช่น ปรอท สเตียรอยด์ ไฮโดรควิโนน": "Cosmetics must not contain substances banned by the FDA, such as mercury, steroids, or hydroquinone.",
    "มาตรฐาน มอก. (TIS)": "TIS Standards (TIS)",
    "อุปกรณ์ไฟฟ้า/อิเล็กทรอนิกส์หลายรายการต้องมีมาตรฐาน มอก. เช่น สายชาร์จ อะแดปเตอร์ หม้อแปลง": "Several electrical/electronic items must comply with TIS standards, e.g., chargers, adapters, transformers.",
    "อุปกรณ์ที่มีคลื่นวิทยุต้องขอ กสทช.": "Radio Wave Devices require NBTC Permit",
    "อุปกรณ์ที่ใช้คลื่นความถี่วิทยุ (Wi-Fi, Bluetooth, 5G) อาจต้องขอใบอนุญาตจาก กสทช.": "Devices utilizing radio frequencies (Wi-Fi, Bluetooth, 5G) may require an NBTC license.",
    "สารเคมีอันตรายต้องขออนุญาต": "Hazardous Chemicals require Permits",
    "สารเคมีอันตรายต้องขอใบอนุญาตจากกรมโรงงานอุตสาหกรรม และต้องมี MSDS (Material Safety Data Sheet)": "Hazardous chemicals require a permit from the Department of Industrial Works and must have an MSDS.",
    "อัตราภาษีสูงมาก": "Very High Duty Rates",
    "ยานพาหนะมีอัตราอากรขาเข้าสูงมาก (40-80%) และอาจมีภาษีสรรพสามิตเพิ่มเติม": "Vehicles are subject to very high import duty rates (40-80%) and may incur additional excise taxes.",
    "การนำเข้ารถยนต์ต้องขอใบอนุญาตจากกระทรวงพาณิชย์ และต้องผ่านมาตรฐาน มอก.": "Importing cars requires a license from the Ministry of Commerce and must pass TIS standards.",
    "ต้องมีใบรับรองสุขอนามัยพืช": "Phytosanitary Certificate Required",
    "สินค้าเกษตรต้องมี Phytosanitary Certificate จากประเทศต้นทาง และอาจต้องกักกันพืช": "Agricultural products require a Phytosanitary Certificate from the exporting country and may require quarantine.",

    // Checklist items translations
    "ลงทะเบียนผู้นำเข้า": "Register Importer",
    "สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs": "Register as an importer with the Customs Department and request a Digital Certificate for e-Customs.",
    "สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate": "Register as an importer with the Customs Department and request a Digital Certificate.",
    "บัตรประชาชน/หนังสือเดินทาง": "ID Card / Passport",
    "หนังสือจดทะเบียนบริษัท": "Company Registration Certificate",
    "Digital Certificate": "Digital Certificate",
    "ตรวจสอบพิกัดศุลกากร (HS Code)": "Check HS Code",
    "หาพิกัดอัตราศุลกากร (HS Code) ของสินค้าที่ต้องการนำเข้า เพื่อทราบอัตราอากรและข้อกำหนด": "Find the HS Code of the imported item to determine duty rates and requirements.",
    "หาพิกัดอัตราศุลกากรของสินค้าอาหาร อัตราอากรอาหารมักอยู่ที่ 30-50%": "Determine the HS Code for food products. Food duty rates usually range between 30-50%.",
    "HS Code 8 หลัก": "8-Digit HS Code",
    "HS Code": "HS Code",
    "ตรวจสอบว่าสินค้าต้องขอใบอนุญาตหรือไม่": "Check Import Permit Requirements",
    "สินค้าบางประเภทต้องขออนุญาตจากหน่วยงานที่เกี่ยวข้อง เช่น อย., กรมวิชาการเกษตร, สำนักงาน กสทช.": "Certain items require permits from relevant agencies such as the FDA, Department of Agriculture, or NBTC.",
    "ใบอนุญาตนำเข้า (ถ้ามี)": "Import Permit (if applicable)",
    "เตรียมเอกสารการค้า": "Prepare Trade Documents",
    "จัดเตรียมเอกสารให้ครบถ้วน ข้อมูลต้องตรงกันทุกเอกสาร (ชื่อ, จำนวน, มูลค่า)": "Prepare all documents completely. Information must match across all documents (name, quantity, value).",
    "Commercial Invoice": "Commercial Invoice",
    "Packing List": "Packing List",
    "Bill of Lading / Air Waybill": "Bill of Lading / Air Waybill",
    "B/L or AWB": "B/L or AWB",
    "ขอหนังสือรับรองแหล่งกำเนิดสินค้า (CO)": "Obtain Certificate of Origin (CO)",
    "หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี ต้องมี Certificate of Origin จากประเทศต้นทาง": "To claim FTA tax preferences, a Certificate of Origin from the exporting country is required.",
    "Certificate of Origin (CO)": "Certificate of Origin (CO)",
    "Certificate of Origin": "Certificate of Origin",
    "จัดหา Freight Forwarder / Customs Broker": "Hire Freight Forwarder / Customs Broker",
    "แนะนำให้ใช้ตัวแทนออกของ (Customs Broker) ที่มีใบอนุญาตเพื่อดำเนินพิธีการศุลกากร": "Hiring a licensed Customs Broker is recommended to handle customs clearance procedures.",
    "สัญญาจ้างตัวแทน": "Broker Contract",
    "ยื่นใบขนสินค้าขาเข้า (e-Import)": "File Import Declaration (e-Import)",
    "ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร ระบบจะตรวจสอบข้อมูลอัตโนมัติ": "Submit the import declaration via the e-Customs system; the system will validate data automatically.",
    "ยื่นใบขนสินค้าผ่านระบบ e-Customs พร้อมแนบเอกสารประกอบ": "Submit the import declaration via e-Customs along with supporting documents.",
    "ยื่นใบขนผ่านระบบ e-Customs": "Submit import declaration via e-Customs.",
    "ใบขนสินค้า (Customs Declaration)": "Customs Declaration",
    "ใบขนสินค้า": "Customs Declaration",
    "ชำระอากรและภาษี": "Pay Duties and Taxes",
    "ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment ของกรมศุลกากร": "Pay import duty and 7% VAT via the e-Payment system of the Customs Department.",
    "ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment": "Pay import duty and 7% VAT via e-Payment.",
    "ชำระอากรขาเข้า (อิเล็กทรอนิกส์มักอยู่ที่ 0-10%) + VAT 7%": "Pay import duty (electronics usually 0-10%) + 7% VAT.",
    "ใบเสร็จชำระอากร": "Duty Payment Receipt",
    "ใบเสร็จ VAT": "VAT Receipt",
    "ใบเสร็จ": "Payment Receipt",
    "รอตรวจปล่อยสินค้า": "Awaiting Cargo Release",
    "สินค้าจะถูกจัดเข้า Green Line (ไม่ตรวจ) หรือ Red Line (ต้องตรวจ) ตามระดับความเสี่ยง": "Goods are sorted into Green Line (no inspection) or Red Line (physical inspection) based on risk profile.",
    "รับสินค้า": "Collect Goods",
    "เมื่อผ่านการตรวจปล่อยแล้ว สามารถรับสินค้าจากท่าเรือ/สนามบินได้": "Once cleared, you can retrieve the goods from the port or airport.",
    "เมื่อผ่านการตรวจปล่อยจากศุลกากรและ อย. แล้ว สามารถรับสินค้าได้": "Collect the goods after customs and FDA clearance.",
    "รับสินค้าหลังผ่านการตรวจปล่อย": "Collect goods after cargo release.",
    "ใบปล่อยสินค้า (Delivery Order)": "Delivery Order",
    "ใบปล่อยสินค้า": "Delivery Order",
    "ขอใบอนุญาตนำเข้าอาหาร (อย.)": "Request Food Import License (FDA)",
    "ยื่นขออนุญาตนำเข้าอาหารจากสำนักงานคณะกรรมการอาหารและยา (อย.) ต้องขอก่อนนำเข้า": "Apply for a food import license from the Food and Drug Administration (FDA) prior to shipment.",
    "ใบอนุญาตนำเข้าอาหาร": "Food Import Permit",
    "ฉลากอาหาร (ภาษาไทย)": "Food Label (Thai)",
    "ผลวิเคราะห์คุณภาพ": "Quality Analysis Report",
    "เตรียมเอกสารการค้า + ใบรับรองสุขอนามัย": "Prepare Trade & Health Certificates",
    "นอกจากเอกสารปกติ ต้องมี Health Certificate และ Phytosanitary Certificate (สินค้าพืช)": "In addition to standard documents, a Health Certificate and Phytosanitary Certificate (for plants) are required.",
    "Health Certificate": "Health Certificate",
    "Phytosanitary Certificate": "Phytosanitary Certificate",
    "ตรวจสอบจาก อย. ที่ด่านอาหารและยา": "FDA Inspection at Port of Entry",
    "สินค้าอาหารจะถูกตรวจสอบที่ด่านอาหารและยา ก่อนปล่อยออกจากท่าเรือ/สนามบิน": "Food products are inspected at the FDA checkpoint prior to release from port/airport.",
    "ผลการตรวจสอบจาก อย.": "FDA Inspection Result",
    "จดแจ้งเครื่องสำอาง / ขออนุญาตยา": "Register Cosmetics / Request Drug Permit",
    "เครื่องสำอางต้องจดแจ้งกับ อย. ก่อนนำเข้า ยาต้องขอใบอนุญาตนำเข้ายาแผนปัจจุบัน": "Cosmetics must be registered with the FDA before import. Medicine requires a modern drug import license.",
    "ใบจดแจ้งเครื่องสำอาง / ใบอนุญาตนำเข้ายา": "Cosmetics Notification / Drug Import License",
    "รายการส่วนผสม (INCI)": "Ingredient List (INCI)",
    "ฉลากภาษาไทย": "Thai Label",
    "ตรวจสอบสารต้องห้ามในส่วนผสม": "Check Prohibited Ingredients",
    "ตรวจสอบว่าผลิตภัณฑ์ไม่มีสารต้องห้ามตามประกาศ อย.": "Verify that the product contains no prohibited substances announced by the FDA.",
    "Certificate of Analysis (COA)": "Certificate of Analysis (COA)",
    "MSDS": "MSDS (Material Safety Data Sheet)",
    "ตรวจสอบจาก อย.": "FDA Inspection",
    "สินค้าจะถูกตรวจสอบที่ด่านอาหารและยา": "Goods will be inspected at the FDA checkpoint.",
    "ผลการตรวจสอบ": "Inspection Result",
    "ตรวจสอบ HS Code และข้อกำหนด มอก.": "Verify HS Code & TIS Requirements",
    "สินค้าอิเล็กทรอนิกส์บางชนิดต้องมีมาตรฐาน มอก. (TIS) และอาจต้องขอใบอนุญาตจาก กสทช.": "Some electronic products require TIS industrial standards and may need NBTC permits.",
    "ใบรับรอง มอก. (ถ้ามี)": "TIS Certificate (if applicable)",
    "ใบอนุญาต กสทช. (ถ้ามี)": "NBTC Permit (if applicable)",
    "อิเล็กทรอนิกส์หลายรายการได้สิทธิ FTA อัตราอากร 0%": "Many electronics qualify for FTA preferences, reducing duty to 0%.",
    "ลงทะเบียนผู้ส่งออก": "Register as Exporter",
    "สมัครเป็นผู้ส่งออกกับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs": "Register as an exporter with the Customs Department and request a Digital Certificate for e-Customs.",
    "ตรวจสอบกฎระเบียบของประเทศปลายทาง": "Check Destination Country Regulations",
    "ศึกษาข้อกำหนดการนำเข้าของประเทศปลายทาง เช่น มาตรฐาน, ฉลาก, ใบอนุญาต": "Study import requirements of the destination country, e.g., standards, labeling, licenses.",
    "กฎระเบียบประเทศปลายทาง": "Destination Regulations",
    "ตรวจสอบว่าสินค้าเป็นสินค้าควบคุมส่งออกหรือไม่": "Verify Export Control Status",
    "สินค้าบางประเภทต้องขออนุญาตก่อนส่งออก เช่น ข้าว, น้ำตาล, อาวุธ, โบราณวัตถุ": "Certain items require authorization before export, e.g., rice, sugar, weapons, antiques.",
    "ใบอนุญาตส่งออก (ถ้ามี)": "Export Permit (if applicable)",
    "จัดเตรียม Invoice, Packing List และเอกสารขนส่ง": "Prepare Invoice, Packing List, and Transport Docs",
    "ขอ CO จากกรมการค้าต่างประเทศ หรือหอการค้าไทย เพื่อให้ผู้ซื้อใช้สิทธิ FTA": "Apply for a CO from the Department of Foreign Trade or Thai Chamber of Commerce for the buyer's FTA benefits.",
    "ยื่นใบขนสินค้าขาออก (e-Export)": "File Export Declaration (e-Export)",
    "ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร": "Submit the export declaration via the Customs Department's e-Customs system.",
    "ใบขนสินค้าขาออก": "Export Declaration",
    "นำสินค้าเข้าท่าเรือ/สนามบิน": "Deliver Cargo to Port/Airport",
    "นำสินค้าไปยังท่าเรือหรือสนามบินตามที่ระบุ พร้อมเอกสารประกอบ": "Deliver cargo to the specified port or airport along with required documents.",
    "ตรวจปล่อยสินค้าขาออก": "Customs Clearance (Export)",
    "รอการตรวจปล่อยจากศุลกากร (ส่วนใหญ่สินค้าส่งออกจะเข้า Green Line)": "Await customs release (most export goods are routed through the Green Line).",
    // Added dynamically
    "Certificate of Analysis": "Certificate of Analysis",
    "GitHub Repository": "GitHub Repository",
    "brand-sub": "Smart Trade Assistant",
    "กรมปศุสัตว์": "Department of Livestock Development",
    "กรมวิชาการเกษตร": "Department of Agriculture",
    "กรมศิลปากร": "Fine Arts Department",
    "กรมศุลกากร": "Customs Department",
    "กรมสรรพสามิต + กรมศุลกากร": "Excise Department + Customs Department",
    "การส่งออกพระพุทธรูปหรือโบราณวัตถุต้องขออนุญาตจากกรมศิลปากร พระพุทธรูปสูงเกิน 13 ซม. ต้องมีใบอนุญาต": "Exporting Buddha images or antiques requires permission from the Fine Arts Department. Buddha images taller than 13 cm require a permit.",
    "ขอ Certificate of Origin (CO)": "Request Certificate of Origin (CO)",
    "จัดเตรียมเอกสารครบถ้วน": "Prepare complete documents",
    "ชำระอากรขาเข้า + VAT 7%": "Pay Import Duty + 7% VAT",
    "ต้องขอใบอนุญาตจากนายทะเบียนอาวุธปืน สำนักงานตำรวจแห่งชาติ": "Requires a permit from the Firearms Registrar, Royal Thai Police",
    "ต้องขอใบอนุญาตนำเข้ายาจาก อย. ก่อนนำเข้า สำหรับใช้ส่วนตัวต้องมีใบรับรองแพทย์และนำเข้าได้ไม่เกิน 30 วัน": "Requires drug import license from FDA before import. For personal use, a medical certificate is required and max 30-day supply.",
    "ต้องขอใบอนุญาตนำเข้าอาหารจาก อย. ต้องมีฉลากภาษาไทย และผ่านการตรวจสอบคุณภาพ": "Requires food import license from FDA. Must have Thai label and pass quality inspection.",
    "ต้องขึ้นทะเบียนกับ CAAT และ กสทช. ก่อนใช้งาน น้ำหนักเกิน 2 กก. ต้องขอใบอนุญาตเพิ่มเติม": "Must register with CAAT and NBTC before use. Drones over 2 kg require additional permits.",
    "ต้องจดแจ้งเครื่องสำอางกับ อย. ก่อนจำหน่าย ต้องมีฉลากภาษาไทยและไม่มีสารต้องห้าม": "Cosmetics must be registered with FDA before sale. Must have Thai label and no prohibited substances.",
    "ต้องมีใบรับรองสุขภาพสัตว์ (Health Certificate) จากประเทศต้นทาง และขอใบอนุญาตนำเข้าจากกรมปศุสัตว์": "Requires Health Certificate from origin country and import permit from Department of Livestock Development.",
    "ต้องมีใบรับรองสุขอนามัยพืช (Phytosanitary Certificate) จากประเทศต้นทาง และอาจต้องขออนุญาตนำเข้าจากกรมวิชาการเกษตร": "Requires Phytosanitary Certificate from origin country and may require import permit from Department of Agriculture.",
    "นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 200 มวน หรือยาสูบ 250 กรัม": "Import for sale requires permit. Personal use limited to 200 cigarettes or 250g tobacco.",
    "นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาตจากกรมสรรพสามิต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 1 ลิตร (ปลอดอากร)": "Import for sale requires permit from Excise Department. Personal use limited to 1 liter (duty-free).",
    "บัตรประชาชน": "ID Card",
    "ผลวิเคราะห์": "Analysis Report",
    "ยื่นใบขนสินค้า (e-Import)": "Submit Import Declaration (e-Import)",
    "สมัครเป็นผู้นำเข้ากับกรมศุลกากร": "Register as an importer with Customs",
    "สำนักงาน กสทช. (NBTC)": "NBTC",
    "สำนักงานการบินพลเรือนแห่งประเทศไทย (CAAT) + กสทช.": "CAAT + NBTC",
    "สำนักงานคณะกรรมการอาหารและยา (อย.)": "Food and Drug Administration (FDA)",
    "สำนักงานตำรวจแห่งชาติ": "Royal Thai Police",
    "หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี": "To claim FTA tax preferences",
    "ห้ามนำเข้า ขาย และครอบครองในประเทศไทย ตามคำสั่งคณะกรรมการคุ้มครองผู้บริโภค มีโทษจำคุกสูงสุด 5 ปี หรือปรับสูงสุด 500,000 บาท": "Import, sale, and possession in Thailand are strictly prohibited. Penalty up to 5 years imprisonment or 500,000 THB fine.",
    "ห้ามนำเข้า-ส่งออกสัตว์ป่าและผลิตภัณฑ์จากสัตว์ป่าที่อยู่ในบัญชี CITES ตามพระราชบัญญัติสงวนและคุ้มครองสัตว์ป่า": "Import-export of wildlife and products listed in CITES is prohibited under the Wildlife Conservation and Protection Act.",
    "ห้ามนำเข้าสินค้าที่ละเมิดลิขสิทธิ์ เครื่องหมายการค้า หรือสิทธิบัตร มีโทษจำคุกและปรับ": "Import of goods infringing copyright, trademark, or patent is prohibited. Subject to imprisonment and fine.",
    "ห้ามนำเข้าสิ่งพิมพ์ ภาพ หรือสื่อลามกอนาจารทุกรูปแบบ": "Import of obscene printed materials, pictures, or media in any form is prohibited.",
    "ห้ามนำเข้าเงินตราปลอม เหรียญปลอม หรือดวงตราปลอมของรัฐบาลโดยเด็ดขาด": "Import of counterfeit currency, fake coins, or fake government seals is strictly prohibited.",
    "ห้ามนำเข้าและส่งออกโดยเด็ดขาด ตามพระราชบัญญัติยาเสพติดให้โทษ ผู้ฝ่าฝืนมีโทษจำคุกสูงสุดตลอดชีวิตหรือประหารชีวิต": "Strictly prohibited for import and export under the Narcotics Act. Violators face life imprisonment or death penalty.",
    "เครื่องวิทยุคมนาคมต้องขอใบอนุญาตจาก กสทช. ก่อนนำเข้า": "Radio communication equipment requires a permit from NBTC before import.",
    "ใบขึ้นทะเบียน CAAT": "CAAT Registration Certificate",
    "ใบจดแจ้งเครื่องสำอาง": "Cosmetics Notification Certificate",
    "ใบรับรองการฉีดวัคซีน": "Vaccination Certificate",
    "ใบรับรองแพทย์ (กรณีส่วนตัว)": "Medical Certificate (Personal Use)",
    "ใบอนุญาต กสทช.": "NBTC Permit",
    "ใบอนุญาตขาย": "Sale Permit",
    "ใบอนุญาตจากกรมศิลปากร": "Permit from Fine Arts Department",
    "ใบอนุญาตนำเข้า": "Import Permit",
    "ใบอนุญาตนำเข้า (บางชนิด)": "Import Permit (Certain Types)",
    "ใบอนุญาตนำเข้ายา": "Drug Import License",
    "ใบอนุญาตนำเข้าสัตว์": "Animal Import License",
    "ใบอนุญาตนำเข้าอาวุธปืน": "Firearms Import License",
    "ใบอนุญาตนำเข้าเครื่องวิทยุคมนาคม": "Radio Communication Import License",
    "สินค้าทั่วไป": "General Goods",
    "นำเข้า": "Import",
    "ส่งออก": "Export",
    "ความคืบหน้า": "Progress",
    "กรอกข้อมูล": "Enter Data",
    "หมวดหมู่สินค้า": "Product Category",
    "ราคาสินค้า (Cost)": "Product Cost",
    "ค่าประกัน (Insurance)": "Insurance",
    "ค่าขนส่ง (Freight)": "Freight",
    "อัตราอากรขาเข้า (กำหนดเอง)": "Customs Duty Rate",
    "ผลการคำนวณ": "Calculation Result",
    "มูลค่า CIF": "CIF Value",
    "อากรขาเข้า": "Import Duty",
    "หมายเหตุ:": "Note:",
    "การคำนวณนี้เป็นการประมาณการเบื้องต้น อัตราอากรจริงขึ้นอยู่กับพิกัดศุลกากร (HS Code) ของสินค้า สินค้าบางรายการอาจมีภาษีสรรพสามิตเพิ่มเติม กรุณาตรวจสอบกับกรมศุลกากรอีกครั้ง": "This calculation is an initial estimate. Actual duty rates depend on the HS Code of the product. Some items may have additional excise taxes. Please verify with the Customs Department.",
    "ไม่พบข้อมูลข้อจำกัด/ข้อห้าม": "No restrictions/prohibitions found",
    "ไม่มีข้อจำกัดพิเศษ": "No special restrictions",
    "สำหรับสินค้านี้ในฐานข้อมูลเบื้องต้น อย่างไรก็ตาม ควรตรวจสอบกับกรมศุลกากรอีกครั้งก่อนดำเนินการ": "for this product in the preliminary database. However, please verify with the Customs Department before proceeding.",
    "พิมพ์ชื่อสินค้าเพื่อตรวจสอบ": "Type product name to check",
    "ลองค้นหา:": "Try searching:",
    "ไม่พบข้อมูลคำเตือนพิเศษ": "No special warnings found",
    "ไม่มีข้อควรระวังพิเศษสำหรับเส้นทางและสินค้านี้ในฐานข้อมูลเบื้องต้น": "No special precautions for this route and product in the preliminary database.",
    "กรุณาเลือกประเทศต้นทางและปลายทางให้ครบถ้วน": "Please select both origin and destination countries."
  }
};

// Translation helper function
function t(key) {
  const lang = (typeof state !== 'undefined' && state.lang) || 'th';
  if (TRANSLATIONS[lang] && TRANSLATIONS[lang][key] !== undefined) {
    return TRANSLATIONS[lang][key];
  }
  // Fallback to the other language if key not found in active language
  const otherLang = lang === 'th' ? 'en' : 'th';
  if (TRANSLATIONS[otherLang] && TRANSLATIONS[otherLang][key] !== undefined) {
    return TRANSLATIONS[otherLang][key];
  }
  return key;
}
