// ============================================
// TradePilot AI — Data Layer
// ============================================

/// ---- Countries ----
const COUNTRIES = [
  { code: 'TH', name: 'ไทย', enName: 'Thailand', flag: '🇹🇭' },
  { code: 'CN', name: 'จีน', enName: 'China', flag: '🇨🇳' },
  { code: 'JP', name: 'ญี่ปุ่น', enName: 'Japan', flag: '🇯🇵' },
  { code: 'US', name: 'สหรัฐอเมริกา', enName: 'United States', flag: '🇺🇸' },
  { code: 'GB', name: 'สหราชอาณาจักร', enName: 'United Kingdom', flag: '🇬🇧' },
  { code: 'DE', name: 'เยอรมนี', enName: 'Germany', flag: '🇩🇪' },
  { code: 'VN', name: 'เวียดนาม', enName: 'Vietnam', flag: '🇻🇳' },
  { code: 'MY', name: 'มาเลเซีย', enName: 'Malaysia', flag: '🇲🇾' },
  { code: 'SG', name: 'สิงคโปร์', enName: 'Singapore', flag: '🇸🇬' },
  { code: 'KR', name: 'เกาหลีใต้', enName: 'South Korea', flag: '🇰🇷' },
  { code: 'TW', name: 'ไต้หวัน', enName: 'Taiwan', flag: '🇹🇼' },
  { code: 'IN', name: 'อินเดีย', enName: 'India', flag: '🇮🇳' },
  { code: 'AU', name: 'ออสเตรเลีย', enName: 'Australia', flag: '🇦🇺' },
  { code: 'ID', name: 'อินโดนีเซีย', enName: 'Indonesia', flag: '🇮🇩' },
  { code: 'PH', name: 'ฟิลิปปินส์', enName: 'Philippines', flag: '🇵🇭' },
  { code: 'AF', name: 'อัฟกานิสถาน', enName: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AL', name: 'แอลเบเนีย', enName: 'Albania', flag: '🇦🇱' },
  { code: 'DZ', name: 'แอลจีเรีย', enName: 'Algeria', flag: '🇩🇿' },
  { code: 'AD', name: 'อันดอร์รา', enName: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', name: 'แองโกลา', enName: 'Angola', flag: '🇦🇴' },
  { code: 'AG', name: 'แอนติกาและบาร์บูดา', enName: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'AR', name: 'อาร์เจนตินา', enName: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', name: 'อาร์เมเนีย', enName: 'Armenia', flag: '🇦🇲' },
  { code: 'AT', name: 'ออสเตรีย', enName: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', name: 'อาเซอร์ไบจาน', enName: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BS', name: 'บาฮามาส', enName: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', name: 'บาห์เรน', enName: 'Bahrain', flag: '🇧🇭' },
  { code: 'BD', name: 'บังกลาเทศ', enName: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', name: 'บาร์เบโดส', enName: 'Barbados', flag: '🇧🇧' },
  { code: 'BY', name: 'เบลารุส', enName: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', name: 'เบลเยียม', enName: 'Belgium', flag: '🇧🇪' },
  { code: 'BZ', name: 'เบลีซ', enName: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'เบนิน', enName: 'Benin', flag: '🇧🇯' },
  { code: 'BT', name: 'ภูฏาน', enName: 'Bhutan', flag: '🇧🇹' },
  { code: 'BO', name: 'โบลิเวีย', enName: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', name: 'บอสเนียและเฮอร์เซโกวีนา', enName: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BW', name: 'บอตสวานา', enName: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', name: 'บราซิล', enName: 'Brazil', flag: '🇧🇷' },
  { code: 'BN', name: 'บรูไน', enName: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', name: 'บัลแกเรีย', enName: 'Bulgaria', flag: '🇧🇬' },
  { code: 'BF', name: 'บูร์กินาฟาโซ', enName: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'บุรุนดี', enName: 'Burundi', flag: '🇧🇮' },
  { code: 'KH', name: 'กัมพูชา', enName: 'Cambodia', flag: '🇰🇭' },
  { code: 'CM', name: 'แคเมอรูน', enName: 'Cameroon', flag: '🇨🇲' },
  { code: 'CA', name: 'แคนาดา', enName: 'Canada', flag: '🇨🇦' },
  { code: 'CV', name: 'เคปเวิร์ด', enName: 'Cape Verde', flag: '🇨🇻' },
  { code: 'CF', name: 'สาธารณรัฐแอฟริกากลาง', enName: 'Central African Republic', flag: '🇨🇫' },
  { code: 'TD', name: 'ชาด', enName: 'Chad', flag: '🇹🇩' },
  { code: 'CL', name: 'ชิลี', enName: 'Chile', flag: '🇨🇱' },
  { code: 'CO', name: 'โคลอมเบีย', enName: 'Colombia', flag: '🇨🇴' },
  { code: 'KM', name: 'คอโมรอส', enName: 'Comoros', flag: '🇰🇲' },
  { code: 'CG', name: 'คองโก', enName: 'Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'สาธารณรัฐประชาธิปไตยคองโก', enName: 'Democratic Republic of the Congo', flag: '🇨🇩' },
  { code: 'CR', name: 'คอสตาริกา', enName: 'Costa Rica', flag: '🇨🇷' },
  { code: 'HR', name: 'โครเอเชีย', enName: 'Croatia', flag: '🇭🇷' },
  { code: 'CU', name: 'คิวบา', enName: 'Cuba', flag: '🇨🇺' },
  { code: 'CY', name: 'ไซปรัส', enName: 'Cyprus', flag: '🇨🇾' },
  { code: 'CZ', name: 'เช็กเกีย', enName: 'Czechia', flag: '🇨🇿' },
  { code: 'DK', name: 'เดนมาร์ก', enName: 'Denmark', flag: '🇩🇰' },
  { code: 'DJ', name: 'จิบูตี', enName: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', name: 'โดมินิกา', enName: 'Dominica', flag: '🇩🇲' },
  { code: 'DO', name: 'สาธารณรัฐโดมินิกัน', enName: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'EC', name: 'เอกวาดอร์', enName: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', name: 'อียิปต์', enName: 'Egypt', flag: '🇪🇬' },
  { code: 'SV', name: 'เอลซัลวาดอร์', enName: 'El Salvador', flag: '🇸🇻' },
  { code: 'GQ', name: 'อิเควทอเรียลกินี', enName: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'ER', name: 'เอริเทรีย', enName: 'Eritrea', flag: '🇪🇷' },
  { code: 'EE', name: 'เอสโตเนีย', enName: 'Estonia', flag: '🇪🇪' },
  { code: 'SZ', name: 'เอสวาตีนี', enName: 'Eswatini', flag: '🇸🇿' },
  { code: 'ET', name: 'เอธิโอเปีย', enName: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FJ', name: 'ฟิจิ', enName: 'Fiji', flag: '🇫🇯' },
  { code: 'FI', name: 'ฟินแลนด์', enName: 'Finland', flag: '🇫🇮' },
  { code: 'FR', name: 'ฝรั่งเศส', enName: 'France', flag: '🇫🇷' },
  { code: 'GA', name: 'กาบอง', enName: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'แกมเบีย', enName: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', name: 'จอร์เจีย', enName: 'Georgia', flag: '🇬🇪' },
  { code: 'GH', name: 'กานา', enName: 'Ghana', flag: '🇬🇭' },
  { code: 'GR', name: 'กรีซ', enName: 'Greece', flag: '🇬🇷' },
  { code: 'GD', name: 'เกรเนดา', enName: 'Grenada', flag: '🇬🇩' },
  { code: 'GT', name: 'กัวเตมาลา', enName: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', name: 'กินี', enName: 'Guinea', flag: '🇬🇳' },
  { code: 'GW', name: 'กินี-บิสเซา', enName: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'กายอานา', enName: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'เฮติ', enName: 'Haiti', flag: '🇭🇹' },
  { code: 'HN', name: 'ฮอนดูรัส', enName: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', name: 'ฮังการี', enName: 'Hungary', flag: '🇭🇺' },
  { code: 'IS', name: 'ไอซ์แลนด์', enName: 'Iceland', flag: '🇮🇸' },
  { code: 'IR', name: 'อิหร่าน', enName: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', name: 'อิรัก', enName: 'Iraq', flag: '🇮🇶' },
  { code: 'IE', name: 'ไอร์แลนด์', enName: 'Ireland', flag: '🇮🇪' },
  { code: 'IL', name: 'อิสราเอล', enName: 'Israel', flag: '🇮🇱' },
  { code: 'IT', name: 'อิตาลี', enName: 'Italy', flag: '🇮🇹' },
  { code: 'CI', name: 'โกตดิวัวร์', enName: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'JM', name: 'จาเมกา', enName: 'Jamaica', flag: '🇯🇲' },
  { code: 'JO', name: 'จอร์แดน', enName: 'Jordan', flag: '🇯🇴' },
  { code: 'KZ', name: 'คาซัคสถาน', enName: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', name: 'เคนยา', enName: 'Kenya', flag: '🇰🇪' },
  { code: 'KI', name: 'คิริบาส', enName: 'Kiribati', flag: '🇰🇮' },
  { code: 'KP', name: 'เกาหลีเหนือ', enName: 'North Korea', flag: '🇰🇵' },
  { code: 'KW', name: 'คูเวต', enName: 'Kuwait', flag: '🇰🇼' },
  { code: 'KG', name: 'คีร์กีซสถาน', enName: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'LA', name: 'ลาว', enName: 'Laos', flag: '🇱🇦' },
  { code: 'LV', name: 'ลัตเวีย', enName: 'Latvia', flag: '🇱🇻' },
  { code: 'LB', name: 'เลบานอน', enName: 'Lebanon', flag: '🇱🇧' },
  { code: 'LS', name: 'เลโซโท', enName: 'Lesotho', flag: '🇱🇸' },
  { code: 'LR', name: 'ไลบีเรีย', enName: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'ลิเบีย', enName: 'Libya', flag: '🇱🇾' },
  { code: 'LI', name: 'ลิกเตนสไตน์', enName: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'ลิทัวเนีย', enName: 'Lithuania', flag: '🇱🇹' },
  { code: 'LU', name: 'ลักเซมเบิร์ก', enName: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MG', name: 'มาดากัสการ์', enName: 'Madagascar', flag: '🇲🇬' },
  { code: 'MW', name: 'มาลาวี', enName: 'Malawi', flag: '🇲🇼' },
  { code: 'MV', name: 'มัลดีฟส์', enName: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', name: 'มาลี', enName: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'มอลตา', enName: 'Malta', flag: '🇲🇹' },
  { code: 'MH', name: 'หมู่เกาะมาร์แชลล์', enName: 'Marshall Islands', flag: '🇲🇭' },
  { code: 'MR', name: 'มอริเตเนีย', enName: 'Mauritania', flag: '🇲🇷' },
  { code: 'MU', name: 'มอริเชียส', enName: 'Mauritius', flag: '🇲🇺' },
  { code: 'MX', name: 'เม็กซิโก', enName: 'Mexico', flag: '🇲🇽' },
  { code: 'FM', name: 'ไมโครนีเซีย', enName: 'Micronesia', flag: '🇫🇲' },
  { code: 'MD', name: 'มอลโดวา', enName: 'Moldova', flag: '🇲🇩' },
  { code: 'MC', name: 'โมนาโก', enName: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', name: 'มองโกเลีย', enName: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', name: 'มอนเตเนโกร', enName: 'Montenegro', flag: '🇲🇪' },
  { code: 'MA', name: 'โมร็อกโก', enName: 'Morocco', flag: '🇲🇦' },
  { code: 'MZ', name: 'โมซัมบิก', enName: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', name: 'เมียนมา', enName: 'Myanmar', flag: '🇲🇲' },
  { code: 'NA', name: 'นามิเบีย', enName: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', name: 'นาอูรู', enName: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'เนปาล', enName: 'Nepal', flag: '🇳🇵' },
  { code: 'NL', name: 'เนเธอร์แลนด์', enName: 'Netherlands', flag: '🇳🇱' },
  { code: 'NZ', name: 'นิวซีแลนด์', enName: 'New Zealand', flag: '🇳🇿' },
  { code: 'NI', name: 'นิการากัว', enName: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'ไนเจอร์', enName: 'Niger', flag: '🇳🇪' },
  { code: 'NG', name: 'ไนจีเรีย', enName: 'Nigeria', flag: '🇳🇬' },
  { code: 'NO', name: 'นอร์เวย์', enName: 'Norway', flag: '🇳🇴' },
  { code: 'OM', name: 'โอมาน', enName: 'Oman', flag: '🇴🇲' },
  { code: 'PK', name: 'ปากีสถาน', enName: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'ปาเลา', enName: 'Palau', flag: '🇵🇼' },
  { code: 'PA', name: 'ปานามา', enName: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'ปาปัวนิวกินี', enName: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'PY', name: 'ปารากวัย', enName: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'เปรู', enName: 'Peru', flag: '🇵🇪' },
  { code: 'PL', name: 'โปแลนด์', enName: 'Poland', flag: '🇵🇱' },
  { code: 'PT', name: 'โปรตุเกส', enName: 'Portugal', flag: '🇵🇹' },
  { code: 'QA', name: 'กาตาร์', enName: 'Qatar', flag: '🇶🇦' },
  { code: 'RO', name: 'โรมาเนีย', enName: 'Romania', flag: '🇷🇴' },
  { code: 'RU', name: 'รัสเซีย', enName: 'Russia', flag: '🇷🇺' },
  { code: 'RW', name: 'รวันดา', enName: 'Rwanda', flag: '🇷🇼' },
  { code: 'KN', name: 'เซนต์คิตส์และเนวิส', enName: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: 'LC', name: 'เซนต์ลูเซีย', enName: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'VC', name: 'เซนต์วินเซนต์และเกรนาดีนส์', enName: 'Saint Vincent and the Grenadines', flag: '🇨🇻' },
  { code: 'WS', name: 'ซามัว', enName: 'Samoa', flag: '🇼🇸' },
  { code: 'SM', name: 'ซานมารีโน', enName: 'San Marino', flag: '🇸🇲' },
  { code: 'ST', name: 'เซาตูเมและปรินซิปี', enName: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: 'SA', name: 'ซาอุดีอาระเบีย', enName: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'SN', name: 'เซเนกัล', enName: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', name: 'เซอร์เบีย', enName: 'Serbia', flag: '🇷🇸' },
  { code: 'SC', name: 'เซเชลส์', enName: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'เซียร์ราลีโอน', enName: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SK', name: 'สโลวาเกีย', enName: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', name: 'สโลวีเนีย', enName: 'Slovenia', flag: '🇸🇮' },
  { code: 'SB', name: 'หมู่เกาะโซโลมอน', enName: 'Solomon Islands', flag: '🇸🇧' },
  { code: 'SO', name: 'โซมาเลีย', enName: 'Somalia', flag: '🇸🇴' },
  { code: 'ZA', name: 'แอฟริกาใต้', enName: 'South Africa', flag: '🇿🇦' },
  { code: 'SS', name: 'เซาท์ซูดาน', enName: 'South Sudan', flag: '🇸🇸' },
  { code: 'ES', name: 'สเปน', enName: 'Spain', flag: '🇪🇸' },
  { code: 'LK', name: 'ศรีลังกา', enName: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SD', name: 'ซูดาน', enName: 'Sudan', flag: '🇸🇩' },
  { code: 'SR', name: 'ซูรินาม', enName: 'Suriname', flag: '🇸🇷' },
  { code: 'SE', name: 'สวีเดน', enName: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', name: 'สวิตเซอร์แลนด์', enName: 'Switzerland', flag: '🇨🇭' },
  { code: 'SY', name: 'ซีเรีย', enName: 'Syria', flag: '🇸🇾' },
  { code: 'TJ', name: 'ทาจิกิสถาน', enName: 'Tajikistan', flag: '🇹🇯' },
  { code: 'TZ', name: 'แทนซาเนีย', enName: 'Tanzania', flag: '🇹🇿' },
  { code: 'TL', name: 'ติมอร์-เลสเต', enName: 'Timor-Leste', flag: '🇹🇱' },
  { code: 'TG', name: 'โตโก', enName: 'Togo', flag: '🇹🇬' },
  { code: 'TO', name: 'ตองกา', enName: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'ตรินิแดดและโตเบโก', enName: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'ตูนิเซีย', enName: 'Tunisia', flag: '🇹🇳' },
  { code: 'TR', name: 'ตุรกี', enName: 'Turkey', flag: '🇹🇷' },
  { code: 'TM', name: 'ทิวร์กเมนิสถาน', enName: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'TV', name: 'ตูวาลู', enName: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UG', name: 'ยูแกนดา', enName: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', name: 'ยูเครน', enName: 'Ukraine', flag: '🇺🇦' },
  { code: 'AE', name: 'สหรัฐอาหรับเอมิเรตส์', enName: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'UY', name: 'อุรุกวัย', enName: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', name: 'อุซเบกิสถาน', enName: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VU', name: 'วานูอาตู', enName: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VA', name: 'นครรัฐวาติกัน', enName: 'Vatican City', flag: '🇻🇦' },
  { code: 'VE', name: 'เวเนซุเอลา', enName: 'Venezuela', flag: '🇻🇪' },
  { code: 'YE', name: 'เยเมน', enName: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', name: 'แซมเบีย', enName: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'ซิมบับเว', enName: 'Zimbabwe', flag: '🇿🇼' }
];

// ---- Product Categories ----
const PRODUCT_CATEGORIES = [
  { id: 'food', name: 'อาหารและเครื่องดื่ม', icon: 'soup', dutyRate: 40 },
  { id: 'cosmetics', name: 'เครื่องสำอาง / ยา / เวชภัณฑ์', icon: 'sparkles', dutyRate: 30 },
  { id: 'electronics', name: 'อิเล็กทรอนิกส์', icon: 'smartphone', dutyRate: 5 },
  { id: 'textiles', name: 'เสื้อผ้า / สิ่งทอ', icon: 'shirt', dutyRate: 30 },
  { id: 'machinery', name: 'เครื่องจักร / อุปกรณ์', icon: 'settings', dutyRate: 5 },
  { id: 'chemicals', name: 'เคมีภัณฑ์', icon: 'flask-conical', dutyRate: 3 },
  { id: 'agriculture', name: 'สินค้าเกษตร', icon: 'sprout', dutyRate: 35 },
  { id: 'vehicles', name: 'ยานพาหนะ / อะไหล่', icon: 'car', dutyRate: 60 },
  { id: 'jewelry', name: 'อัญมณี / เครื่องประดับ', icon: 'gem', dutyRate: 20 },
  { id: 'general', name: 'สินค้าทั่วไป', icon: 'package', dutyRate: 15 },
];

// ---- VAT Rate ----
const VAT_RATE = 0.07; // 7%

// ---- Checklists ----
const CHECKLISTS = {
  import: {
    general: [
      {
        title: 'ลงทะเบียนผู้นำเข้า',
        desc: 'สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs',
        docs: ['บัตรประชาชน/หนังสือเดินทาง', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'ตรวจสอบพิกัดศุลกากร (HS Code)',
        desc: 'หาพิกัดอัตราศุลกากร (HS Code) ของสินค้าที่ต้องการนำเข้า เพื่อทราบอัตราอากรและข้อกำหนด',
        docs: ['HS Code 8 หลัก'],
      },
      {
        title: 'ตรวจสอบว่าสินค้าต้องขอใบอนุญาตหรือไม่',
        desc: 'สินค้าบางประเภทต้องขออนุญาตจากหน่วยงานที่เกี่ยวข้อง เช่น อย., กรมวิชาการเกษตร, สำนักงาน กสทช.',
        docs: ['ใบอนุญาตนำเข้า (ถ้ามี)'],
      },
      {
        title: 'เตรียมเอกสารการค้า',
        desc: 'จัดเตรียมเอกสารให้ครบถ้วน ข้อมูลต้องตรงกันทุกเอกสาร (ชื่อ, จำนวน, มูลค่า)',
        docs: ['Commercial Invoice', 'Packing List', 'Bill of Lading / Air Waybill'],
      },
      {
        title: 'ขอหนังสือรับรองแหล่งกำเนิดสินค้า (CO)',
        desc: 'หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี ต้องมี Certificate of Origin จากประเทศต้นทาง',
        docs: ['Certificate of Origin (CO)'],
      },
      {
        title: 'จัดหา Freight Forwarder / Customs Broker',
        desc: 'แนะนำให้ใช้ตัวแทนออกของ (Customs Broker) ที่มีใบอนุญาตเพื่อดำเนินพิธีการศุลกากร',
        docs: ['สัญญาจ้างตัวแทน'],
      },
      {
        title: 'ยื่นใบขนสินค้าขาเข้า (e-Import)',
        desc: 'ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร ระบบจะตรวจสอบข้อมูลอัตโนมัติ',
        docs: ['ใบขนสินค้า (Customs Declaration)'],
      },
      {
        title: 'ชำระอากรและภาษี',
        desc: 'ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment ของกรมศุลกากร',
        docs: ['ใบเสร็จชำระอากร', 'ใบเสร็จ VAT'],
      },
      {
        title: 'รอตรวจปล่อยสินค้า',
        desc: 'สินค้าจะถูกจัดเข้า Green Line (ไม่ตรวจ) หรือ Red Line (ต้องตรวจ) ตามระดับความเสี่ยง',
        docs: [],
      },
      {
        title: 'รับสินค้า',
        desc: 'เมื่อผ่านการตรวจปล่อยแล้ว สามารถรับสินค้าจากท่าเรือ/สนามบินได้',
        docs: ['ใบปล่อยสินค้า (Delivery Order)'],
      },
    ],
    food: [
      {
        title: 'ลงทะเบียนผู้นำเข้า',
        desc: 'สมัครเป็นผู้นำเข้ากับกรมศุลกากร และขอ Digital Certificate',
        docs: ['บัตรประชาชน/หนังสือเดินทาง', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'ขอใบอนุญาตนำเข้าอาหาร (อย.)',
        desc: 'ยื่นขออนุญาตนำเข้าอาหารจากสำนักงานคณะกรรมการอาหารและยา (อย.) ต้องขอก่อนนำเข้า',
        docs: ['ใบอนุญาตนำเข้าอาหาร', 'ฉลากอาหาร (ภาษาไทย)', 'ผลวิเคราะห์คุณภาพ'],
      },
      {
        title: 'ตรวจสอบพิกัดศุลกากร (HS Code)',
        desc: 'หาพิกัดอัตราศุลกากรของสินค้าอาหาร อัตราอากรอาหารมักอยู่ที่ 30-50%',
        docs: ['HS Code 8 หลัก'],
      },
      {
        title: 'เตรียมเอกสารการค้า + ใบรับรองสุขอนามัย',
        desc: 'นอกจากเอกสารปกติ ต้องมี Health Certificate และ Phytosanitary Certificate (สินค้าพืช)',
        docs: ['Commercial Invoice', 'Packing List', 'B/L or AWB', 'Health Certificate', 'Phytosanitary Certificate'],
      },
      {
        title: 'ขอ Certificate of Origin (CO)',
        desc: 'หากต้องการใช้สิทธิ FTA เพื่อลดหย่อนภาษี',
        docs: ['Certificate of Origin'],
      },
      {
        title: 'ยื่นใบขนสินค้า (e-Import)',
        desc: 'ยื่นใบขนสินค้าผ่านระบบ e-Customs พร้อมแนบเอกสารประกอบ',
        docs: ['ใบขนสินค้า'],
      },
      {
        title: 'ตรวจสอบจาก อย. ที่ด่านอาหารและยา',
        desc: 'สินค้าอาหารจะถูกตรวจสอบที่ด่านอาหารและยา ก่อนปล่อยออกจากท่าเรือ/สนามบิน',
        docs: ['ผลการตรวจสอบจาก อย.'],
      },
      {
        title: 'ชำระอากรและภาษี',
        desc: 'ชำระอากรขาเข้า + VAT 7% ผ่านระบบ e-Payment',
        docs: ['ใบเสร็จชำระอากร'],
      },
      {
        title: 'รับสินค้า',
        desc: 'เมื่อผ่านการตรวจปล่อยจากศุลกากรและ อย. แล้ว สามารถรับสินค้าได้',
        docs: ['ใบปล่อยสินค้า'],
      },
    ],
    cosmetics: [
      {
        title: 'ลงทะเบียนผู้นำเข้า',
        desc: 'สมัครเป็นผู้นำเข้ากับกรมศุลกากร',
        docs: ['บัตรประชาชน', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'จดแจ้งเครื่องสำอาง / ขออนุญาตยา',
        desc: 'เครื่องสำอางต้องจดแจ้งกับ อย. ก่อนนำเข้า ยาต้องขอใบอนุญาตนำเข้ายาแผนปัจจุบัน',
        docs: ['ใบจดแจ้งเครื่องสำอาง / ใบอนุญาตนำเข้ายา', 'รายการส่วนผสม (INCI)', 'ฉลากภาษาไทย'],
      },
      {
        title: 'ตรวจสอบสารต้องห้ามในส่วนผสม',
        desc: 'ตรวจสอบว่าผลิตภัณฑ์ไม่มีสารต้องห้ามตามประกาศ อย.',
        docs: ['Certificate of Analysis (COA)', 'MSDS'],
      },
      {
        title: 'เตรียมเอกสารการค้า',
        desc: 'จัดเตรียมเอกสารครบถ้วน',
        docs: ['Commercial Invoice', 'Packing List', 'B/L or AWB'],
      },
      {
        title: 'ยื่นใบขนสินค้า (e-Import)',
        desc: 'ยื่นใบขนผ่านระบบ e-Customs',
        docs: ['ใบขนสินค้า'],
      },
      {
        title: 'ตรวจสอบจาก อย.',
        desc: 'สินค้าจะถูกตรวจสอบที่ด่านอาหารและยา',
        docs: ['ผลการตรวจสอบ'],
      },
      {
        title: 'ชำระอากรและภาษี',
        desc: 'ชำระอากรขาเข้า + VAT 7%',
        docs: ['ใบเสร็จ'],
      },
      {
        title: 'รับสินค้า',
        desc: 'รับสินค้าหลังผ่านการตรวจปล่อย',
        docs: ['ใบปล่อยสินค้า'],
      },
    ],
    electronics: [
      {
        title: 'ลงทะเบียนผู้นำเข้า',
        desc: 'สมัครเป็นผู้นำเข้ากับกรมศุลกากร',
        docs: ['บัตรประชาชน', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'ตรวจสอบ HS Code และข้อกำหนด มอก.',
        desc: 'สินค้าอิเล็กทรอนิกส์บางชนิดต้องมีมาตรฐาน มอก. (TIS) และอาจต้องขอใบอนุญาตจาก กสทช.',
        docs: ['HS Code', 'ใบรับรอง มอก. (ถ้ามี)', 'ใบอนุญาต กสทช. (ถ้ามี)'],
      },
      {
        title: 'เตรียมเอกสารการค้า',
        desc: 'จัดเตรียมเอกสารครบถ้วน',
        docs: ['Commercial Invoice', 'Packing List', 'B/L or AWB'],
      },
      {
        title: 'ขอ Certificate of Origin (CO)',
        desc: 'อิเล็กทรอนิกส์หลายรายการได้สิทธิ FTA อัตราอากร 0%',
        docs: ['Certificate of Origin'],
      },
      {
        title: 'ยื่นใบขนสินค้า (e-Import)',
        desc: 'ยื่นใบขนผ่านระบบ e-Customs',
        docs: ['ใบขนสินค้า'],
      },
      {
        title: 'ชำระอากรและภาษี',
        desc: 'ชำระอากรขาเข้า (อิเล็กทรอนิกส์มักอยู่ที่ 0-10%) + VAT 7%',
        docs: ['ใบเสร็จ'],
      },
      {
        title: 'รับสินค้า',
        desc: 'รับสินค้าหลังผ่านการตรวจปล่อย',
        docs: ['ใบปล่อยสินค้า'],
      },
    ],
  },
  export: {
    general: [
      {
        title: 'ลงทะเบียนผู้ส่งออก',
        desc: 'สมัครเป็นผู้ส่งออกกับกรมศุลกากร และขอ Digital Certificate สำหรับระบบ e-Customs',
        docs: ['บัตรประชาชน/หนังสือเดินทาง', 'หนังสือจดทะเบียนบริษัท', 'Digital Certificate'],
      },
      {
        title: 'ตรวจสอบกฎระเบียบของประเทศปลายทาง',
        desc: 'ศึกษาข้อกำหนดการนำเข้าของประเทศปลายทาง เช่น มาตรฐาน, ฉลาก, ใบอนุญาต',
        docs: ['กฎระเบียบประเทศปลายทาง'],
      },
      {
        title: 'ตรวจสอบว่าสินค้าเป็นสินค้าควบคุมส่งออกหรือไม่',
        desc: 'สินค้าบางประเภทต้องขออนุญาตก่อนส่งออก เช่น ข้าว, น้ำตาล, อาวุธ, โบราณวัตถุ',
        docs: ['ใบอนุญาตส่งออก (ถ้ามี)'],
      },
      {
        title: 'เตรียมเอกสารการค้า',
        desc: 'จัดเตรียม Invoice, Packing List และเอกสารขนส่ง',
        docs: ['Commercial Invoice', 'Packing List', 'Bill of Lading / Air Waybill'],
      },
      {
        title: 'ขอหนังสือรับรองแหล่งกำเนิดสินค้า (CO)',
        desc: 'ขอ CO จากกรมการค้าต่างประเทศ หรือหอการค้าไทย เพื่อให้ผู้ซื้อใช้สิทธิ FTA',
        docs: ['Certificate of Origin (CO)'],
      },
      {
        title: 'ยื่นใบขนสินค้าขาออก (e-Export)',
        desc: 'ยื่นใบขนสินค้าผ่านระบบ e-Customs ของกรมศุลกากร',
        docs: ['ใบขนสินค้าขาออก'],
      },
      {
        title: 'นำสินค้าเข้าท่าเรือ/สนามบิน',
        desc: 'นำสินค้าไปยังท่าเรือหรือสนามบินตามที่ระบุ พร้อมเอกสารประกอบ',
        docs: [],
      },
      {
        title: 'ตรวจปล่อยสินค้าขาออก',
        desc: 'รอการตรวจปล่อยจากศุลกากร (ส่วนใหญ่สินค้าส่งออกจะเข้า Green Line)',
        docs: ['ใบปล่อยสินค้า'],
      },
    ],
  },
};

// ---- Prohibited Items ----
const PROHIBITED_ITEMS = [
  {
    keywords: ['ยาเสพติด', 'เฮโรอีน', 'โคเคน', 'ฝิ่น', 'กัญชา', 'ยาบ้า', 'ยาไอซ์', 'กระท่อม', 'narcotics', 'drugs', 'heroin', 'cocaine', 'opium', 'marijuana', 'methamphetamine'],
    name: 'ยาเสพติดให้โทษ',
    status: 'prohibited',
    reason: 'ห้ามนำเข้าและส่งออกโดยเด็ดขาด ตามพระราชบัญญัติยาเสพติดให้โทษ ผู้ฝ่าฝืนมีโทษจำคุกสูงสุดตลอดชีวิตหรือประหารชีวิต',
  },
  {
    keywords: ['บุหรี่ไฟฟ้า', 'vape', 'e-cigarette', 'pod', 'บุหรี่อิเล็กทรอนิกส์', 'น้ำยาบุหรี่', 'iqos', 'juul', 'พอด'],
    name: 'บุหรี่ไฟฟ้า / Vape / IQOS',
    status: 'prohibited',
    reason: 'ห้ามนำเข้า ขาย และครอบครองในประเทศไทย ตามคำสั่งคณะกรรมการคุ้มครองผู้บริโภค มีโทษจำคุกสูงสุด 5 ปี หรือปรับสูงสุด 500,000 บาท',
  },
  {
    keywords: ['สื่อลามก', 'หนังโป๊', 'pornography', 'obscene', 'สื่อลามกอนาจาร'],
    name: 'สื่อลามกอนาจาร',
    status: 'prohibited',
    reason: 'ห้ามนำเข้าสิ่งพิมพ์ ภาพ หรือสื่อลามกอนาจารทุกรูปแบบ',
  },
  {
    keywords: ['สินค้าปลอม', 'ของก๊อป', 'ของเลียนแบบ', 'ละเมิดลิขสิทธิ์', 'counterfeit', 'fake', 'ของปลอม', 'เลียนแบบแบรนด์'],
    name: 'สินค้าปลอม / ละเมิดทรัพย์สินทางปัญญา',
    status: 'prohibited',
    reason: 'ห้ามนำเข้าสินค้าที่ละเมิดลิขสิทธิ์ เครื่องหมายการค้า หรือสิทธิบัตร มีโทษจำคุกและปรับ',
  },
  {
    keywords: ['สัตว์ป่า', 'งาช้าง', 'ivory', 'กระดองเต่า', 'นอแรด', 'หนังจระเข้', 'สัตว์คุ้มครอง', 'CITES', 'wildlife'],
    name: 'สัตว์ป่าคุ้มครอง / ผลิตภัณฑ์จากสัตว์ป่า',
    status: 'prohibited',
    reason: 'ห้ามนำเข้า-ส่งออกสัตว์ป่าและผลิตภัณฑ์จากสัตว์ป่าที่อยู่ในบัญชี CITES ตามพระราชบัญญัติสงวนและคุ้มครองสัตว์ป่า',
  },
  {
    keywords: ['เงินปลอม', 'ธนบัตรปลอม', 'แสตมป์ปลอม', 'ตราปลอม', 'counterfeit currency', 'fake money'],
    name: 'เงินตราปลอม / ตราปลอม',
    status: 'prohibited',
    reason: 'ห้ามนำเข้าเงินตราปลอม เหรียญปลอม หรือดวงตราปลอมของรัฐบาลโดยเด็ดขาด',
  },
];

// ---- Restricted Items (ต้องมีใบอนุญาต) ----
const RESTRICTED_ITEMS = [
  {
    keywords: ['ยา', 'เวชภัณฑ์', 'ยาแผนปัจจุบัน', 'ยาสมุนไพร', 'วัคซีน', 'medicine', 'pharmaceutical', 'drug', 'ยารักษาโรค', 'อาหารเสริม', 'supplement'],
    name: 'ยา / เวชภัณฑ์ / อาหารเสริม',
    status: 'restricted',
    agency: 'สำนักงานคณะกรรมการอาหารและยา (อย.)',
    reason: 'ต้องขอใบอนุญาตนำเข้ายาจาก อย. ก่อนนำเข้า สำหรับใช้ส่วนตัวต้องมีใบรับรองแพทย์และนำเข้าได้ไม่เกิน 30 วัน',
    docs: ['ใบอนุญาตนำเข้ายา', 'ใบรับรองแพทย์ (กรณีส่วนตัว)'],
  },
  {
    keywords: ['เครื่องสำอาง', 'ครีม', 'skincare', 'cosmetic', 'makeup', 'แป้ง', 'ลิปสติก', 'ครีมกันแดด', 'เซรั่ม', 'serum'],
    name: 'เครื่องสำอาง',
    status: 'restricted',
    agency: 'สำนักงานคณะกรรมการอาหารและยา (อย.)',
    reason: 'ต้องจดแจ้งเครื่องสำอางกับ อย. ก่อนจำหน่าย ต้องมีฉลากภาษาไทยและไม่มีสารต้องห้าม',
    docs: ['ใบจดแจ้งเครื่องสำอาง', 'รายการส่วนผสม (INCI)', 'Certificate of Analysis'],
  },
  {
    keywords: ['อาวุธ', 'ปืน', 'กระสุน', 'ระเบิด', 'firearms', 'weapon', 'ammunition', 'gun', 'explosive'],
    name: 'อาวุธปืน / กระสุน / วัตถุระเบิด',
    status: 'restricted',
    agency: 'สำนักงานตำรวจแห่งชาติ',
    reason: 'ต้องขอใบอนุญาตจากนายทะเบียนอาวุธปืน สำนักงานตำรวจแห่งชาติ',
    docs: ['ใบอนุญาตนำเข้าอาวุธปืน'],
  },
  {
    keywords: ['พืช', 'เมล็ดพันธุ์', 'ผลไม้', 'ผัก', 'ดอกไม้', 'ต้นไม้', 'plant', 'seed', 'fruit', 'vegetable', 'flower'],
    name: 'พืช / เมล็ดพันธุ์ / ผลไม้สด',
    status: 'restricted',
    agency: 'กรมวิชาการเกษตร',
    reason: 'ต้องมีใบรับรองสุขอนามัยพืช (Phytosanitary Certificate) จากประเทศต้นทาง และอาจต้องขออนุญาตนำเข้าจากกรมวิชาการเกษตร',
    docs: ['Phytosanitary Certificate', 'ใบอนุญาตนำเข้า (บางชนิด)'],
  },
  {
    keywords: ['สัตว์', 'สัตว์เลี้ยง', 'สุนัข', 'แมว', 'ปลา', 'นก', 'animal', 'pet', 'dog', 'cat', 'bird', 'fish', 'สัตว์มีชีวิต'],
    name: 'สัตว์มีชีวิต / ผลิตภัณฑ์จากสัตว์',
    status: 'restricted',
    agency: 'กรมปศุสัตว์',
    reason: 'ต้องมีใบรับรองสุขภาพสัตว์ (Health Certificate) จากประเทศต้นทาง และขอใบอนุญาตนำเข้าจากกรมปศุสัตว์',
    docs: ['Health Certificate', 'ใบอนุญาตนำเข้าสัตว์', 'ใบรับรองการฉีดวัคซีน'],
  },
  {
    keywords: ['พระพุทธรูป', 'โบราณวัตถุ', 'ศิลปวัตถุ', 'antique', 'buddha', 'artifact', 'โบราณ'],
    name: 'พระพุทธรูป / โบราณวัตถุ / ศิลปวัตถุ',
    status: 'restricted',
    agency: 'กรมศิลปากร',
    reason: 'การส่งออกพระพุทธรูปหรือโบราณวัตถุต้องขออนุญาตจากกรมศิลปากร พระพุทธรูปสูงเกิน 13 ซม. ต้องมีใบอนุญาต',
    docs: ['ใบอนุญาตจากกรมศิลปากร'],
  },
  {
    keywords: ['วิทยุสื่อสาร', 'วอลกี้ทอลกี้', 'เครื่องส่งวิทยุ', 'radio', 'transceiver', 'walkie talkie', 'อุปกรณ์โทรคมนาคม', 'telecom'],
    name: 'อุปกรณ์โทรคมนาคม / วิทยุสื่อสาร',
    status: 'restricted',
    agency: 'สำนักงาน กสทช. (NBTC)',
    reason: 'เครื่องวิทยุคมนาคมต้องขอใบอนุญาตจาก กสทช. ก่อนนำเข้า',
    docs: ['ใบอนุญาตนำเข้าเครื่องวิทยุคมนาคม'],
  },
  {
    keywords: ['โดรน', 'drone', 'UAV', 'อากาศยานไร้คนขับ'],
    name: 'โดรน / อากาศยานไร้คนขับ',
    status: 'restricted',
    agency: 'สำนักงานการบินพลเรือนแห่งประเทศไทย (CAAT) + กสทช.',
    reason: 'ต้องขึ้นทะเบียนกับ CAAT และ กสทช. ก่อนใช้งาน น้ำหนักเกิน 2 กก. ต้องขอใบอนุญาตเพิ่มเติม',
    docs: ['ใบขึ้นทะเบียน CAAT', 'ใบอนุญาต กสทช.'],
  },
  {
    keywords: ['สุรา', 'เหล้า', 'เบียร์', 'ไวน์', 'แอลกอฮอล์', 'alcohol', 'beer', 'wine', 'liquor', 'whisky', 'whiskey', 'vodka'],
    name: 'สุรา / เครื่องดื่มแอลกอฮอล์',
    status: 'restricted',
    agency: 'กรมสรรพสามิต + กรมศุลกากร',
    reason: 'นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาตจากกรมสรรพสามิต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 1 ลิตร (ปลอดอากร)',
    docs: ['ใบอนุญาตนำเข้า', 'ใบอนุญาตขาย'],
  },
  {
    keywords: ['บุหรี่', 'ยาสูบ', 'ซิการ์', 'cigarette', 'tobacco', 'cigar'],
    name: 'บุหรี่ / ยาสูบ',
    status: 'restricted',
    agency: 'กรมสรรพสามิต + กรมศุลกากร',
    reason: 'นำเข้าเพื่อจำหน่ายต้องขอใบอนุญาต ของใช้ส่วนตัวนำเข้าได้ไม่เกิน 200 มวน หรือยาสูบ 250 กรัม',
    docs: ['ใบอนุญาตนำเข้า'],
  },
  {
    keywords: ['อาหาร', 'ขนม', 'อาหารแปรรูป', 'อาหารกระป๋อง', 'food', 'snack', 'canned food', 'instant noodle', 'มาม่า', 'บะหมี่', 'ซอส', 'เครื่องปรุง'],
    name: 'อาหาร / อาหารแปรรูป',
    status: 'restricted',
    agency: 'สำนักงานคณะกรรมการอาหารและยา (อย.)',
    reason: 'ต้องขอใบอนุญาตนำเข้าอาหารจาก อย. ต้องมีฉลากภาษาไทย และผ่านการตรวจสอบคุณภาพ',
    docs: ['ใบอนุญาตนำเข้าอาหาร', 'ฉลากภาษาไทย', 'ผลวิเคราะห์'],
  },
];

// ---- Warnings & Regulations ----
const WARNINGS = {
  // Global warnings (แสดงทุกกรณี)
  global: [
    {
      type: 'critical',
      icon: 'alert-octagon',
      title: 'ต้องลงทะเบียนเป็นผู้นำเข้า/ส่งออก',
      text: 'ก่อนดำเนินการนำเข้าหรือส่งออก ต้องลงทะเบียนกับกรมศุลกากรและมี Digital Certificate เพื่อใช้ระบบ e-Customs',
    },
    {
      type: 'important',
      icon: 'banknote',
      title: 'สินค้าทุกรายการต้องเสียภาษี VAT 7%',
      text: 'ตั้งแต่ปี 2024 สินค้านำเข้าทุกรายการรวมถึงมูลค่าต่ำกว่า 1,500 บาท ต้องเสียภาษีมูลค่าเพิ่ม (VAT) 7%',
    },
    {
      type: 'info',
      icon: 'file-text',
      title: 'เอกสารต้องตรงกันทุกฉบับ',
      text: 'ข้อมูลใน Invoice, Packing List และ Bill of Lading ต้องตรงกัน (ชื่อ, จำนวน, มูลค่า) หากไม่ตรงอาจถูกกักสินค้า',
    },
  ],
  // Country-specific warnings
  country: {
    CN: [
      {
        type: 'important',
        icon: 'flag',
        title: 'สิทธิ FTA กับจีน (ACFTA)',
        text: 'สินค้าจากจีนอาจได้สิทธิลดหย่อนภาษีภายใต้ ASEAN-China FTA (ACFTA) ต้องมี Certificate of Origin Form E',
      },
      {
        type: 'info',
        icon: 'alert-triangle',
        title: 'ระวังสินค้าไม่ได้มาตรฐาน',
        text: 'สินค้าจากจีนบางรายการอาจไม่ผ่านมาตรฐาน มอก. ควรขอใบรับรองคุณภาพจากผู้ผลิตก่อนสั่งซื้อ',
      },
    ],
    JP: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA กับญี่ปุ่น (JTEPA)',
        text: 'สินค้าจากญี่ปุ่นอาจได้สิทธิลดหย่อนภาษีภายใต้ Japan-Thailand Economic Partnership Agreement (JTEPA)',
      },
    ],
    US: [
      {
        type: 'important',
        icon: 'flag',
        title: 'ไม่มี FTA กับสหรัฐฯ',
        text: 'ไทยไม่มีข้อตกลง FTA กับสหรัฐอเมริกา สินค้าจะเสียภาษีในอัตราปกติ (MFN Rate)',
      },
      {
        type: 'info',
        icon: 'package',
        title: 'มาตรฐาน FDA สำหรับอาหาร/ยา',
        text: 'หากส่งออกอาหาร/ยาไปสหรัฐฯ ต้องผ่านมาตรฐาน US FDA ซึ่งมีข้อกำหนดเข้มงวด',
      },
    ],
    GB: [
      {
        type: 'info',
        icon: 'flag',
        title: 'กฎระเบียบหลัง Brexit',
        text: 'หลัง Brexit สหราชอาณาจักรมีกฎระเบียบนำเข้าแยกจาก EU ควรตรวจสอบข้อกำหนดล่าสุด',
      },
    ],
    VN: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA ภายใต้ AFTA/ATIGA',
        text: 'สินค้าจากเวียดนามได้สิทธิลดหย่อนภาษีภายใต้ ASEAN Trade in Goods Agreement (ATIGA)',
      },
    ],
    MY: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA ภายใต้ AFTA/ATIGA',
        text: 'สินค้าจากมาเลเซียได้สิทธิลดหย่อนภาษีภายใต้ ATIGA อัตราอากรส่วนใหญ่ 0%',
      },
    ],
    SG: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA ภายใต้ AFTA/ATIGA',
        text: 'สินค้าจากสิงคโปร์ได้สิทธิลดหย่อนภาษีภายใต้ ATIGA',
      },
    ],
    KR: [
      {
        type: 'info',
        icon: 'flag',
        title: 'สิทธิ FTA กับเกาหลีใต้ (AKFTA)',
        text: 'สินค้าจากเกาหลีใต้อาจได้สิทธิลดหย่อนภาษีภายใต้ ASEAN-Korea FTA (AKFTA)',
      },
    ],
    DE: [
      {
        type: 'info',
        icon: 'flag',
        title: 'กฎระเบียบ EU',
        text: 'เยอรมนีเป็นสมาชิก EU สินค้าต้องเป็นไปตามมาตรฐาน CE Marking และกฎระเบียบ EU',
      },
    ],
  },
  // Product-category specific warnings
  product: {
    food: [
      {
        type: 'critical',
        icon: 'soup',
        title: 'ต้องขออนุญาต อย. ก่อนนำเข้าอาหาร',
        text: 'อาหารทุกประเภทต้องขอใบอนุญาตนำเข้าจาก อย. และต้องมีฉลากภาษาไทย รวมถึงแสดงวันผลิต/หมดอายุ',
      },
      {
        type: 'important',
        icon: 'tag',
        title: 'ฉลากภาษาไทยบังคับ',
        text: 'อาหารนำเข้าต้องมีฉลากภาษาไทยแสดงชื่อ, ส่วนประกอบ, วันผลิต, วันหมดอายุ, เลข อย.',
      },
    ],
    cosmetics: [
      {
        type: 'critical',
        icon: 'sparkles',
        title: 'ต้องจดแจ้งเครื่องสำอางกับ อย.',
        text: 'เครื่องสำอางทุกชนิดต้องจดแจ้งกับ อย. ก่อนจำหน่าย ต้องมีฉลากภาษาไทยและส่วนประกอบตาม INCI',
      },
      {
        type: 'important',
        icon: 'ban',
        title: 'ตรวจสอบสารต้องห้าม',
        text: 'เครื่องสำอางต้องไม่มีสารต้องห้ามตามประกาศ อย. เช่น ปรอท สเตียรอยด์ ไฮโดรควิโนน',
      },
    ],
    electronics: [
      {
        type: 'important',
        icon: 'smartphone',
        title: 'มาตรฐาน มอก. (TIS)',
        text: 'อุปกรณ์ไฟฟ้า/อิเล็กทรอนิกส์หลายรายการต้องมีมาตรฐาน มอก. เช่น สายชาร์จ อะแดปเตอร์ หม้อแปลง',
      },
      {
        type: 'info',
        icon: 'radio',
        title: 'อุปกรณ์ที่มีคลื่นวิทยุต้องขอ กสทช.',
        text: 'อุปกรณ์ที่ใช้คลื่นความถี่วิทยุ (Wi-Fi, Bluetooth, 5G) อาจต้องขอใบอนุญาตจาก กสทช.',
      },
    ],
    chemicals: [
      {
        type: 'critical',
        icon: 'flask-conical',
        title: 'สารเคมีอันตรายต้องขออนุญาต',
        text: 'สารเคมีอันตรายต้องขอใบอนุญาตจากกรมโรงงานอุตสาหกรรม และต้องมี MSDS (Material Safety Data Sheet)',
      },
    ],
    vehicles: [
      {
        type: 'critical',
        icon: 'car',
        title: 'อัตราภาษีสูงมาก',
        text: 'ยานพาหนะมีอัตราอากรขาเข้าสูงมาก (40-80%) และอาจมีภาษีสรรพสามิตเพิ่มเติม',
      },
      {
        type: 'important',
        icon: 'file-text',
        title: 'ต้องขอใบอนุญาตนำเข้า',
        text: 'การนำเข้ารถยนต์ต้องขอใบอนุญาตจากกระทรวงพาณิชย์ และต้องผ่านมาตรฐาน มอก.',
      },
    ],
    agriculture: [
      {
        type: 'critical',
        icon: 'sprout',
        title: 'ต้องมีใบรับรองสุขอนามัยพืช',
        text: 'สินค้าเกษตรต้องมี Phytosanitary Certificate จากประเทศต้นทาง และอาจต้องกักกันพืช',
      },
    ],
  },
};

// ---- FTA Information (simplified) ----
const FTA_INFO = {
  CN: { name: 'ACFTA (ASEAN-China FTA)', form: 'Form E' },
  JP: { name: 'JTEPA', form: 'Form JTEPA' },
  KR: { name: 'AKFTA (ASEAN-Korea FTA)', form: 'Form AK' },
  AU: { name: 'TAFTA (Thailand-Australia FTA)', form: 'Form TAFTA' },
  IN: { name: 'AIFTA (ASEAN-India FTA)', form: 'Form AI' },
  VN: { name: 'ATIGA (ASEAN)', form: 'Form D' },
  MY: { name: 'ATIGA (ASEAN)', form: 'Form D' },
  SG: { name: 'ATIGA (ASEAN)', form: 'Form D' },
  ID: { name: 'ATIGA (ASEAN)', form: 'Form D' },
  PH: { name: 'ATIGA (ASEAN)', form: 'Form D' },
};
